<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Thomas Pengilly" />


<title>Brewery Case Study</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.9.1/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-1.49.4/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-1.49.4/plotly-latest.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Brewery_Case_Study.html">Beer Study</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Brewery Case Study</h1>
<h4 class="author">Thomas Pengilly</h4>
<h4 class="date">2/22/2020</h4>

</div>


<div id="section" class="section level143">
<p></p>
</div>
<div id="introduction" class="section level64">
<p>Introduction</p>
<div id="section-1" class="section level143">
<p></p>
</div>
</div>
<div id="our-goal-is-to-provide-any-interesting-or-useful-insights-gained-from-the-analysis-of-the-beer-and-brewery-data-provided-by-budweiser.-in-exploring-the-beer-data-we-will-analyze-variables-including-abv-alcohol-content-by-volume-ibu-international-bitterness-units-the-brewer-brewery-location-beer-style-and-the-volume-in-ounces-of-the-beer-of-interest-in-order-to-find-interesting-correlations.-we-have-found-numerous-insights-about-beer-preferences-across-the-country-and-the-differences-between-the-various-beer-styles-using-both-knn-and-logistic-regression-classifiers.-our-findings-are-presented-below." class="section level1">
<h1>Our goal is to provide any interesting or useful insights gained from the analysis of the beer and brewery data provided by Budweiser. In exploring the beer data we will analyze variables including ABV (alcohol content by volume), IBU (International Bitterness Units), the brewer, brewery location, beer style, and the volume in ounces of the beer of interest in order to find interesting correlations. We have found numerous insights about beer preferences across the country and the differences between the various beer styles using both KNN and logistic regression classifiers. Our findings are presented below.</h1>
</div>
<div id="link-to-rshiny-app-httpstpengilly.shinyapps.ioshinyapp" class="section level1">
<h1>Link to RShiny App: <a href="https://tpengilly.shinyapps.io/ShinyApp/" class="uri">https://tpengilly.shinyapps.io/ShinyApp/</a></h1>
<div id="section-2" class="section level143">
<p></p>
</div>
<div id="section-3" class="section level143">
<p></p>
</div>
<div id="section-4" class="section level143">
<p></p>
</div>
<div id="section-5" class="section level143">
<p></p>
</div>
<div id="analysis-questions" class="section level57">
<p>Analysis Questions</p>
<div id="section-6" class="section level143">
<p></p>
</div>
<div id="section-7" class="section level143">
<p></p>
</div>
<div id="question-1" class="section level60">
<p>Question 1</p>
<div id="section-8" class="section level143">
<p></p>
</div>
</div>
</div>
<div id="how-many-breweries-are-present-in-each-state" class="section level3">
<h3>1. How many breweries are present in each state?</h3>
</div>
</div>
<div id="this-will-load-the-necessary-libraries-read-in-the-brewery-data-summarize-the-number-of-breweries-in-each-state-then-plot-a-barchart-of-the-results." class="section level1">
<h1>This will load the necessary libraries, read in the brewery data, summarize the number of breweries in each state, then plot a barchart of the results.</h1>
<pre class="r"><code># Load required Libraries
library(ggplot2)
library(plyr)
library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.0 --</code></pre>
<pre><code>## &lt;U+2713&gt; tibble  2.1.3     &lt;U+2713&gt; dplyr   0.8.3
## &lt;U+2713&gt; tidyr   1.0.0     &lt;U+2713&gt; stringr 1.4.0
## &lt;U+2713&gt; readr   1.3.1     &lt;U+2713&gt; forcats 0.4.0
## &lt;U+2713&gt; purrr   0.3.3</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::arrange()   masks plyr::arrange()
## x purrr::compact()   masks plyr::compact()
## x dplyr::count()     masks plyr::count()
## x dplyr::failwith()  masks plyr::failwith()
## x dplyr::filter()    masks stats::filter()
## x dplyr::id()        masks plyr::id()
## x dplyr::lag()       masks stats::lag()
## x dplyr::mutate()    masks plyr::mutate()
## x dplyr::rename()    masks plyr::rename()
## x dplyr::summarise() masks plyr::summarise()
## x dplyr::summarize() masks plyr::summarize()</code></pre>
<pre class="r"><code>library(GGally)</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;GGally&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<pre><code>## 
## Attaching package: &#39;GGally&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     nasa</code></pre>
<pre class="r"><code>library(caret)</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## 
## Attaching package: &#39;caret&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     lift</code></pre>
<pre class="r"><code>library(class)
library(e1071)

# Read in brewery data
brewery_data = read.csv(&#39;C:/Users/Tpeng/OneDrive/Documents/SMU/Doing Data Science/Unit 8 Project/Breweries.csv&#39;, header = TRUE, na.strings =c(&#39;&#39;, &#39;NA&#39;))

# Create an object that counts breweries by state, to be used for reordering data
state_counts = data.frame(table(brewery_data$State))
colnames(state_counts)  = c(&quot;State&quot;, &quot;Freq&quot;)
state_counts = state_counts[order(state_counts$Freq),]

# Plot the ordered results
state_counts %&gt;% ggplot(aes(x = reorder(State, Freq), y = Freq, fill = State)) +
  geom_bar(stat = &#39;identity&#39;) + 
  coord_flip() + 
  ggtitle(&#39;Number of Breweries by State&#39;) + 
  ylab(&#39;Count&#39;) + 
  xlab(&#39;State&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
</div>
<div id="this-creates-a-heatmap-for-the-number-of-breweries-in-each-state.-the-number-of-breweries-is-plotted-in-the-center-of-each-state." class="section level1">
<h1>This creates a heatmap for the number of breweries in each state. The number of breweries is plotted in the center of each state.</h1>
<pre class="r"><code>library(ggplot2)
library(maps)</code></pre>
<pre><code>## 
## Attaching package: &#39;maps&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     map</code></pre>
<pre><code>## The following object is masked from &#39;package:plyr&#39;:
## 
##     ozone</code></pre>
<pre class="r"><code>library(dplyr)
library(mapproj)

# Create dataframe with state information and change column names to merge
new_brewery_data = brewery_data
lookup = data.frame(abb = state.abb, State = state.name)
colnames(new_brewery_data)[4] = &quot;abb&quot;
brewery_data2 = merge(new_brewery_data,lookup, by =&quot;abb&quot;, all.x = TRUE, no.dups = F)
brewery_data2 = brewery_data2[!brewery_data2$abb == &#39; DC&#39;,]
levels(brewery_data2$State) = levels(lookup$State)
levels(lookup$abb) = levels(brewery_data2$abb)


for (row in 1:nrow(brewery_data2)){
  abb = as.character(brewery_data2$abb[row])
  abb = trimws(abb)
  brewery_data2$State[row] = state.name[which(state.abb == abb)]
}

# Count breweries in each state and manipulate variables to match states dataframe
NumBreweryMapData = count(brewery_data2, State)
colnames(NumBreweryMapData)[2] = &quot;Breweries&quot;
NumBreweryMapData$region &lt;- tolower(NumBreweryMapData$State)
NumBreweryMapData2 = NumBreweryMapData[-1]
states &lt;- map_data(&quot;state&quot;)

map.df &lt;- merge(states,NumBreweryMapData2, by=&quot;region&quot;, all.x=T)
map.df &lt;- map.df[order(map.df$order),]

# Get rough location of middle of each state to plot number of breweries overtop of the states
tibble = map.df %&gt;% group_by(region) %&gt;% summarise(midlat = mean(c(max(lat), min(lat))), midlong = mean(c(max(long), min(long))))
for (row in 1:nrow(map.df)){
  region = map.df$region[row]
  midlat = tibble[tibble$region == region,]$midlat
  midlong = tibble[tibble$region == region,]$midlong
  map.df$midlat[row] = midlat
  map.df$midlong[row] = midlong
}

ggplot(map.df, aes(x=long,y=lat,group=group)) + 
  geom_polygon(aes(fill=Breweries)) +
  geom_path() + 
  scale_fill_gradientn(colours=rev(heat.colors(10)),na.value=&quot;grey90&quot;) +
  ggtitle(&quot;Number of Breweries in Each State&quot;) +  
  coord_map() + 
  geom_text(label = map.df$Breweries, x = map.df$midlong, y = map.df$midlat) +
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## Warning: Removed 10 rows containing missing values (geom_text).</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
</div>
<div id="the-top-10-states-account-for-over-50-of-all-breweries-nationwide.-what-makes-these-states-so-attractive-is-a-combination-of-factors.-the-top-10-states-have-some-of-the-lowest-excise-taxes-on-beer-nationwide-some-of-the-largest-21-and-older-populations-in-the-country-and-some-of-the-highest-median-incomes-in-the-country.-others-like-colorado-have-a-long-tradition-of-brewing-thanks-to-the-gold-rush-and-coors-creating-a-peculiar-brewing-culture-that-exploded-when-home-brewing-was-legalized-in-1979." class="section level1">
<h1>The top 10 states account for over 50% of all breweries nationwide. What makes these states so attractive is a combination of factors. The top 10 states have some of the lowest excise taxes on beer nationwide, some of the largest 21 and older populations in the country, and some of the highest median incomes in the country. Others, like Colorado, have a long tradition of brewing, thanks to the gold rush and Coors, creating a peculiar brewing culture that exploded when home-brewing was legalized in 1979.</h1>
<div id="section-9" class="section level143">
<p></p>
</div>
<div id="question-2" class="section level60">
<p>Question 2</p>
<div id="section-10" class="section level143">
<p></p>
</div>
</div>
<div id="merge-beer-data-with-the-breweries-data.-print-the-first-and-last-6-observations-to-check-the-merged-file." class="section level3">
<h3>2. Merge beer data with the breweries data. Print the first and last 6 observations to check the merged file.</h3>
</div>
</div>
<div id="the-following-code-reads-in-the-beer-dataset-and-merges-it-with-the-brewery-data-such-that-each-brewery-will-now-contain-the-all-information-regarding-its-beers-present-in-the-beer-dataset.-it-will-then-print-the-first-and-last-6-observations-to-verify-that-it-worked-correctly." class="section level1">
<h1>The following code reads in the beer dataset and merges it with the brewery data such that each brewery will now contain the all information regarding its beers present in the beer dataset. It will then print the first and last 6 observations to verify that it worked correctly.</h1>
<pre class="r"><code># Read in Beer data and merge with brewery data
beer_data = read.csv(&#39;C:/Users/Tpeng/OneDrive/Documents/SMU/Doing Data Science/Unit 8 Project/Beers.csv&#39;, header = TRUE, na.strings = c(&#39;&#39;, &#39;NA&#39;))

dataset = merge(brewery_data, beer_data, by.x = &#39;Brew_ID&#39;, by.y = &#39;Brewery_id&#39;, all = TRUE)

# Print first and last 6 observations
dataset[1:6,]</code></pre>
<pre><code>##   Brew_ID             Name.x        City State        Name.y Beer_ID   ABV IBU
## 1       1 NorthGate Brewing  Minneapolis    MN       Pumpion    2689 0.060  38
## 2       1 NorthGate Brewing  Minneapolis    MN    Stronghold    2688 0.060  25
## 3       1 NorthGate Brewing  Minneapolis    MN   Parapet ESB    2687 0.056  47
## 4       1 NorthGate Brewing  Minneapolis    MN  Get Together    2692 0.045  50
## 5       1 NorthGate Brewing  Minneapolis    MN Maggie&#39;s Leap    2691 0.049  26
## 6       1 NorthGate Brewing  Minneapolis    MN    Wall&#39;s End    2690 0.048  19
##                                 Style Ounces
## 1                         Pumpkin Ale     16
## 2                     American Porter     16
## 3 Extra Special / Strong Bitter (ESB)     16
## 4                        American IPA     16
## 5                  Milk / Sweet Stout     16
## 6                   English Brown Ale     16</code></pre>
<pre class="r"><code>tail(dataset, 6)</code></pre>
<pre><code>##      Brew_ID                        Name.x          City State
## 2405     556         Ukiah Brewing Company         Ukiah    CA
## 2406     557       Butternuts Beer and Ale Garrattsville    NY
## 2407     557       Butternuts Beer and Ale Garrattsville    NY
## 2408     557       Butternuts Beer and Ale Garrattsville    NY
## 2409     557       Butternuts Beer and Ale Garrattsville    NY
## 2410     558 Sleeping Lady Brewing Company     Anchorage    AK
##                         Name.y Beer_ID   ABV IBU                   Style Ounces
## 2405             Pilsner Ukiah      98 0.055  NA         German Pilsener     12
## 2406         Porkslap Pale Ale      49 0.043  NA American Pale Ale (APA)     12
## 2407           Snapperhead IPA      51 0.068  NA            American IPA     12
## 2408         Moo Thunder Stout      50 0.049  NA      Milk / Sweet Stout     12
## 2409  Heinnieweisse Weissebier      52 0.049  NA              Hefeweizen     12
## 2410 Urban Wilderness Pale Ale      30 0.049  NA        English Pale Ale     12</code></pre>
<div id="section-11" class="section level143">
<p></p>
</div>
<div id="question-3" class="section level60">
<p>Question 3</p>
<div id="section-12" class="section level143">
<p></p>
</div>
</div>
<div id="address-the-missing-values-in-each-column-abv-and-ibu." class="section level3">
<h3>3. Address the missing values in each column (ABV and IBU).</h3>
</div>
</div>
<div id="this-code-removes-any-beers-with-a-missing-style-there-are-5.-it-then-calculates-the-average-abv-and-ibu-for-each-style-of-beer-and-assigns-this-value-to-any-beer-of-that-style-with-missing-values." class="section level1">
<h1>This code removes any beers with a missing style (there are 5). It then calculates the average ABV and IBU for each style of beer, and assigns this value to any beer of that style with missing values.</h1>
<pre class="r"><code># Remove beers missing values for Style
dataset = dataset[!is.na(dataset$Style),]

# Calculate average values for ABV and IBU and store in a dataframe
avg_abv = dataset %&gt;% group_by(Style) %&gt;% summarize(meanABV = mean(ABV, na.rm = TRUE))
avg_abv = as.data.frame(avg_abv)

grand_mean_abv = dataset %&gt;% summarize(grand_mean_abv = mean(ABV, na.rm = TRUE))
grand_mean_ibu = dataset %&gt;% summarize(grand_mean_ibu = mean(IBU, na.rm = TRUE))

avg_ibu = dataset %&gt;% group_by(Style) %&gt;% summarize(meanibu  = mean(IBU, na.rm = TRUE))
avg_ibu = as.data.frame(avg_ibu)

# Replace missing average IBU&#39;s with grand mean IBU in IBU dataframe
avg_ibu$meanibu = ifelse(is.na(avg_ibu$meanibu), grand_mean_ibu, avg_ibu$meanibu)

# Replace missing ABV&#39;s and IBU&#39;s in full dataset with averages by Style
for (row in 1:nrow(dataset)){
  
  if(is.na(dataset[row, &#39;ABV&#39;])){
    dataset[row, &#39;ABV&#39;] = avg_abv[avg_abv$Style == dataset$Style[row],]$meanABV[1]
  }
  if(is.na(dataset[row, &#39;IBU&#39;])){
    dataset[row, &#39;IBU&#39;] = avg_ibu[avg_ibu$Style == dataset$Style[row],]$meanibu[1]
  }
}</code></pre>
</div>
<div id="the-missing-values-were-filled-in-with-as-meaningful-data-as-possible-with-the-given-dataset.-the-average-alcohol-content-and-bitterness-rating-was-calculated-for-each-style-of-beer.-any-beers-of-that-style-with-a-missing-value-was-given-the-average-for-that-style.-this-required-removing-the-few-cases-of-beers-with-missing-styles-5-since-these-could-not-contribute-meaningfully-to-the-averages." class="section level1">
<h1>The missing values were filled in with as meaningful data as possible with the given dataset. The average alcohol content and bitterness rating was calculated for each style of beer. Any beers of that style with a missing value was given the average for that style. This required removing the few cases of beers with missing styles (5), since these could not contribute meaningfully to the averages.</h1>
<div id="section-13" class="section level143">
<p></p>
</div>
<div id="question-4" class="section level60">
<p>Question 4</p>
<div id="section-14" class="section level143">
<p></p>
</div>
</div>
<div id="compute-the-median-alcohol-content-and-ibu-for-each-state.-plot-a-bar-chart-to-compare." class="section level3">
<h3>4. Compute the median alcohol content and IBU for each state. Plot a bar chart to compare.</h3>
</div>
</div>
<div id="this-code-computes-the-median-abv-and-ibu-by-state-and-then-prints-the-state-with-the-highest-median-abv-and-ibu.-it-also-creates-a-median-dataframe-that-is-used-for-a-heatmap.-the-state-with-the-highest-median-abv-is-kentucky-that-with-the-highest-median-ibu-is-delaware." class="section level1">
<h1>This code computes the median ABV and IBU by state, and then prints the state with the highest median ABV and IBU. It also creates a median dataframe, that is used for a heatmap. The state with the highest median ABV is Kentucky, that with the highest median IBU is Delaware.</h1>
<pre class="r"><code># Find and display median values
median_abv = dataset %&gt;% group_by(State) %&gt;% summarize(medianABV = median(ABV))
median_abv = as.data.frame(median_abv)

median_ibu = dataset %&gt;% group_by(State) %&gt;% summarize(medianIBU = median(IBU))
median_ibu = as.data.frame(median_ibu)

# Determine which observation has maximum values and output the state
median_abv$State[which.max(median_abv$medianABV)] # Kentucky</code></pre>
<pre><code>## [1]  KY
## 51 Levels:  AK  AL  AR  AZ  CA  CO  CT  DC  DE  FL  GA  HI  IA  ID  IL ...  WY</code></pre>
<pre class="r"><code>median_abv$medianABV[which.max(median_abv$medianABV)]</code></pre>
<pre><code>## [1] 0.06452758</code></pre>
<pre class="r"><code>median_ibu$State[which.max(median_ibu$medianIBU)] # Delaware</code></pre>
<pre><code>## [1]  DE
## 51 Levels:  AK  AL  AR  AZ  CA  CO  CT  DC  DE  FL  GA  HI  IA  ID  IL ...  WY</code></pre>
<pre class="r"><code>median_ibu$medianIBU[which.max(median_ibu$medianIBU)]</code></pre>
<pre><code>## [1] 59.81728</code></pre>
<pre class="r"><code>median_data = merge(median_abv, median_ibu, by = &#39;State&#39;)</code></pre>
</div>
<div id="this-creates-a-bar-chart-for-median-abv-and-ibu-for-each-state." class="section level1">
<h1>This creates a bar chart for median ABV and IBU for each state.</h1>
<pre class="r"><code>median_abv %&gt;% ggplot(aes(x = reorder(State, medianABV, fun = median), y = medianABV)) +
  geom_point(col = &#39;tomato2&#39;, size = 2) +
  geom_segment(aes(x = median_abv$State,
                   xend = State,
                   y = min(median_abv$medianABV),
                   yend = max(median_abv$medianABV)),
                   linetype = &#39;dashed&#39;,
                   size = 0.1) +
  coord_flip() +
  ggtitle(&#39;Median ABV By State&#39;) +
  xlab(&#39;State&#39;) + ylab(&#39;Median ABV&#39;) + 
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>median_ibu %&gt;% ggplot(aes(x = reorder(State, medianIBU, fun = median), y = medianIBU)) +
  geom_point(col = &#39;tomato2&#39;, size = 2) +
  geom_segment(aes(x = median_ibu$State,
                   xend = State,
                   y = min(median_ibu$medianIBU),
                   yend = max(median_ibu$medianIBU)),
                   linetype = &#39;dashed&#39;,
                   size = 0.1) +
  coord_flip() +
  ggtitle(&#39;Median IBU By State&#39;) +
  xlab(&#39;State&#39;) + ylab(&#39;Median IBU&#39;) + 
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
</div>
<div id="this-plots-the-median-abv-and-ibu-by-state-on-a-heatmap-for-an-easy-to-read-summary-of-the-data." class="section level1">
<h1>This plots the median ABV and IBU by state on a heatmap for an easy-to-read summary of the data.</h1>
<pre class="r"><code>library(ggplot2)
library(maps)
library(dplyr)
library(mapproj)

# Create dataframe with state information and change column names to merge
lookup = data.frame(abb = state.abb, State = state.name)
colnames(median_data)[1] = &quot;abb&quot;
median_data2 = merge(median_data,lookup, by =&quot;abb&quot;, all.x = TRUE, no.dups = F)
median_data2 = median_data2[!median_data2$abb == &#39; DC&#39;,]
levels(median_data2$State) = levels(lookup$State)
levels(lookup$abb) = levels(median_data2$abb)

for (row in 1:nrow(median_data2)){
  abb = as.character(median_data2$abb[row])
  abb = trimws(abb)
  median_data2$State[row] = state.name[which(state.abb == abb)]
}

median_data2$region &lt;- tolower(median_data2$State)
states &lt;- map_data(&quot;state&quot;)
map.df &lt;- merge(states,median_data2, by=&quot;region&quot;, all.x=T)
map.df &lt;- map.df[order(map.df$order),]
map.df$Percent = map.df$medianABV * 100

ggplot(map.df, aes(x=long,y=lat,group=group)) + 
  geom_polygon(aes(fill=Percent)) +
  geom_path() + 
  scale_fill_gradientn(colours=rev(rainbow(10)),na.value=&quot;grey90&quot;) +
  ggtitle(&quot;Median ABV in Each State&quot;) +  
  coord_map() + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  labs(fill = &#39;ABV (%)&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>ggplot(map.df, aes(x=long,y=lat,group=group)) + 
  geom_polygon(aes(fill=medianIBU)) +
  geom_path() + 
  scale_fill_gradientn(colours=rev(rainbow(10)),na.value=&quot;grey90&quot;) +
  ggtitle(&quot;Median IBU in Each State&quot;) +  
  coord_map() + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(fill = &#39;IBU Rating&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
</div>
<div id="the-majority-of-the-country-has-a-median-alcohol-content-of-about-5.5-for-beers-with-notable-exceptions-being-kentucky-6.4-and-west-virginia-6.2-and-utah-4.-kentucky-is-world-famous-for-their-bourbon-whiskey-and-this-influences-their-beer-production.-kentucky-craft-beer-is-often-aged-in-whiskey-barrels-which-can-increase-the-abv-due-to-the-residual-whiskey-as-well-as-allowing-some-water-to-evaporate." class="section level1">
<h1>The majority of the country has a median alcohol content of about 5.5% for beers, with notable exceptions being Kentucky (6.4%) and West Virginia (6.2%), and Utah (~4%). Kentucky is world famous for their bourbon whiskey, and this influences their beer production. Kentucky craft beer is often aged in whiskey barrels, which can increase the ABV due to the residual whiskey, as well as allowing some water to evaporate.</h1>
<p>#Utah has much stricter laws regulating alcohol due to the high concentration of Mormon’s and their beliefs regarding alcohol.</p>
</div>
<div id="a-rough-national-median-ibu-rating-is-between-30-40-with-delaware-having-the-highest-60-and-west-virginia-close-behind-at-57.-delaware-and-west-virginia-are-much-higher-than-the-rest-of-the-nation-because-they-have-far-fewer-breweries-than-most-states-but-are-following-the-national-trend-of-brewing-bitter-ipas-and-pale-ales.-the-median-bitterness-rating-is-much-lower-in-the-midwest-than-elsewhere-in-the-country.-this-is-due-to-the-preference-for-ales-over-more-bitter-beer-styles-in-this-region.-we-will-discuss-this-later-in-our-analysis-question-9." class="section level1">
<h1>A rough national median IBU rating is between 30-40, with Delaware having the highest (60), and West Virginia close behind at 57. Delaware and West Virginia are much higher than the rest of the nation because they have far fewer breweries than most states, but are following the national trend of brewing bitter IPA’s and pale ales. The median bitterness rating is much lower in the midwest than elsewhere in the country. This is due to the preference for ales over more bitter beer styles in this region. We will discuss this later in our analysis (question 9).</h1>
<div id="section-15" class="section level143">
<p></p>
</div>
<div id="question-5" class="section level60">
<p>Question 5</p>
<div id="section-16" class="section level143">
<p></p>
</div>
</div>
<div id="which-state-has-the-most-alcoholic-beer-and-which-has-the-most-bitter-beer" class="section level3">
<h3>5. Which state has the most alcoholic beer, and which has the most bitter beer?</h3>
</div>
</div>
<div id="the-following-code-determines-which-states-have-the-highest-beer-abv-and-ibu-and-prints-them-out.-the-state-with-the-highest-abv-beer-is-colorado-12.8-and-the-state-with-the-highest-ibu-is-oregon-138." class="section level1">
<h1>The following code determines which states have the highest beer ABV and IBU, and prints them out. The state with the highest ABV beer is Colorado (12.8%), and the state with the highest IBU is Oregon (138).</h1>
<pre class="r"><code>state_maxABV = dataset$State[which.max(dataset$ABV)]
state_maxIBU = dataset$State[which.max(dataset$IBU)]
state_maxABV # Colorado</code></pre>
<pre><code>## [1]  CO
## 51 Levels:  AK  AL  AR  AZ  CA  CO  CT  DC  DE  FL  GA  HI  IA  ID  IL ...  WY</code></pre>
<pre class="r"><code>dataset$ABV[which.max(dataset$ABV)]</code></pre>
<pre><code>## [1] 0.128</code></pre>
<pre class="r"><code>state_maxIBU # Oregon</code></pre>
<pre><code>## [1]  OR
## 51 Levels:  AK  AL  AR  AZ  CA  CO  CT  DC  DE  FL  GA  HI  IA  ID  IL ...  WY</code></pre>
<pre class="r"><code>dataset$IBU[which.max(dataset$IBU)]</code></pre>
<pre><code>## [1] 138</code></pre>
<pre class="r"><code>max_abv = dataset %&gt;% group_by(State) %&gt;% summarize(maxABV = max(ABV))
max_abv = as.data.frame(max_abv)
max_ibu = dataset %&gt;% group_by(State) %&gt;% summarize(maxIBU = max(IBU))
max_ibu = as.data.frame(max_ibu)
max_data = merge(max_abv, max_ibu, by = &#39;State&#39;)</code></pre>
</div>
<div id="this-creates-a-bar-chart-for-maximum-abv-and-ibu-for-each-state." class="section level1">
<h1>This creates a bar chart for maximum ABV and IBU for each state.</h1>
<pre class="r"><code>max_abv %&gt;% ggplot(aes(x = reorder(State, maxABV, fun = median), y = maxABV)) +
  geom_point(col = &#39;tomato2&#39;, size = 2) +
  geom_segment(aes(x = max_abv$State,
                   xend = State,
                   y = min(max_abv$maxABV),
                   yend = max(max_abv$maxABV)),
                   linetype = &#39;dashed&#39;,
                   size = 0.1) +
  coord_flip() +
  ggtitle(&#39;Max ABV By State&#39;) +
  xlab(&#39;State&#39;) + ylab(&#39;Max ABV&#39;) + 
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>max_ibu %&gt;% ggplot(aes(x = reorder(State, maxIBU, fun = median), y = maxIBU)) +
  geom_point(col = &#39;tomato2&#39;, size = 2) +
  geom_segment(aes(x = max_ibu$State,
                   xend = State,
                   y = min(max_ibu$maxIBU),
                   yend = max(max_ibu$maxIBU)),
                   linetype = &#39;dashed&#39;,
                   size = 0.1) +
  coord_flip() +
  ggtitle(&#39;Max IBU By State&#39;) +
  xlab(&#39;State&#39;) + ylab(&#39;Max IBU&#39;) + 
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
</div>
<div id="this-code-creates-a-heatmap-for-the-max-abv-and-ibu-for-beer-in-each-state." class="section level1">
<h1>This code creates a heatmap for the max ABV and IBU for beer in each state.</h1>
<pre class="r"><code># Manipulate variable names to enable merging dataframes
lookup = data.frame(abb = state.abb, State = state.name)
colnames(max_data)[1] = &quot;abb&quot;
max_data2 = merge(max_data,lookup, by =&quot;abb&quot;, all.x = TRUE, no.dups = F)
max_data2 = max_data2[!max_data2$abb == &#39; DC&#39;,]
levels(max_data2$State) = levels(lookup$State)
levels(lookup$abb) = levels(max_data2$abb)

for (row in 1:nrow(max_data2)){
  abb = as.character(max_data2$abb[row])
  abb = trimws(abb)
  max_data2$State[row] = state.name[which(state.abb == abb)]
}

max_data2$region &lt;- tolower(max_data2$State)
states &lt;- map_data(&quot;state&quot;)

# Merge dataframes
map.df &lt;- merge(states,max_data2, by=&quot;region&quot;, all.x=T)
map.df &lt;- map.df[order(map.df$order),]
map.df$Percent = map.df$maxABV * 100

ggplot(map.df, aes(x=long,y=lat,group=group)) + 
  geom_polygon(aes(fill=maxABV)) +
  geom_path() + 
  scale_fill_gradientn(colours=rev(rainbow(10)),na.value=&quot;grey90&quot;) +
  ggtitle(&quot;Max ABV in Each State&quot;) +  
  coord_map() + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  labs(fill = &#39;ABV (%)&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>ggplot(map.df, aes(x=long,y=lat,group=group)) + 
  geom_polygon(aes(fill=maxIBU)) +
  geom_path() + 
  scale_fill_gradientn(colours=rev(rainbow(10)),na.value=&quot;grey90&quot;) +
  ggtitle(&quot;Max IBU in Each State&quot;) +  
  coord_map() + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(fill = &#39;IBU Rating&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-10-2.png" width="672" /></p>
</div>
<div id="the-state-with-the-highest-alcohol-content-beer-is-colorado-12.8-with-kentucky-in-second-at-12.5.-these-two-states-highest-abv-beers-far-exceed-the-closest-states-because-they-dont-have-regulatory-limits-on-the-maximum-abv-content-like-the-13-states-with-a-limit-of-10-as-seen-in-the-bar-plot-above." class="section level1">
<h1>The state with the highest alcohol content beer is Colorado (12.8%) with Kentucky in second at 12.5%. These two states highest ABV beers far exceed the closest states, because they don’t have regulatory limits on the maximum ABV content like the 13 states with a limit of (10%) as seen in the bar plot above.</h1>
</div>
<div id="the-state-with-the-most-bitter-beer-is-oregon-138-ibu-with-virginia-in-second-at-135.-it-is-interesting-to-note-that-utah-does-not-have-the-weakest-maximum-abv-beer-given-their-alcohol-laws-but-that-arkansas-and-tennessee-have-the-weakest-maximum-abv-beer-and-lowest-maximum-ibu.-since-these-states-have-no-prohibitions-on-alcohol-content-and-are-not-particularly-tough-on-brewers-this-must-be-due-to-personal-preference." class="section level1">
<h1>The state with the most bitter beer is Oregon (138 IBU) with Virginia in second at 135. It is interesting to note that Utah does not have the weakest maximum ABV beer given their alcohol laws, but that Arkansas and Tennessee have the weakest maximum ABV beer and lowest maximum IBU. Since these states have no prohibitions on alcohol content, and are not particularly tough on brewers, this must be due to personal preference.</h1>
<div id="section-17" class="section level143">
<p></p>
</div>
<div id="question-6" class="section level60">
<p>Question 6</p>
<div id="section-18" class="section level143">
<p></p>
<p>###6. Comment on the summary statistics and distribution of ABV</p>
</div>
</div>
</div>
<div id="this-will-calculate-the-summary-statistics-of-abv-for-all-beers" class="section level1">
<h1>This will calculate the summary statistics of ABV for all beers</h1>
<pre class="r"><code># Get summary statistics
summary(dataset$ABV)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.00100 0.05000 0.05647 0.05975 0.06700 0.12800</code></pre>
<pre class="r"><code>mean(dataset$ABV)</code></pre>
<pre><code>## [1] 0.05975184</code></pre>
<pre class="r"><code>sd(dataset$ABV)</code></pre>
<pre><code>## [1] 0.01345838</code></pre>
</div>
<div id="this-plots-overall-distribution-of-abv-in-a-histogram." class="section level1">
<h1>This plots overall distribution of ABV in a histogram.</h1>
<pre class="r"><code># Plot Overall ABV distribution colored by state.
dataset %&gt;% ggplot(aes(fill = State)) +geom_histogram(aes(x = dataset$ABV), binwidth = 0.005)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="this-code-selects-only-popular-beer-styles-n-75-then-plots-histograms-of-the-abv-and-ibus-by-style." class="section level1">
<h1>This code selects only popular beer styles (n &gt; 75), then plots histograms of the ABV and IBU’s by style.</h1>
<pre class="r"><code>popular_beers_tibble = count(dataset, Style)
popular_beers_tibble = popular_beers_tibble %&gt;% filter(popular_beers_tibble$n &gt; 75)
popular_beers = merge(dataset, popular_beers_tibble, by = &#39;Style&#39;, all.x = FALSE, all.y = TRUE)

popular_beers %&gt;% ggplot() + 
  geom_histogram(aes(x = popular_beers$ABV * 100, fill = Style)) + 
  facet_wrap(popular_beers$Style) + theme(legend.position = &#39;none&#39;) +
  xlab(&#39;ABV (%)&#39;)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>popular_beers %&gt;% ggplot() + geom_histogram(aes(x = popular_beers$IBU, fill = Style)) + 
  facet_wrap(popular_beers$Style) + 
  theme(legend.position = &#39;none&#39;) +
  xlab(&#39;IBU Rating&#39;)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
</div>
<div id="the-most-common-abv-is-about-5-5.5-but-there-is-a-niche-market-for-beers-with-higher-abvs-in-the-range-of-6-10.-since-most-people-do-not-buy-a-beer-because-of-its-alcohol-content-this-is-an-interesting-revelation-that-warrants-further-investigation.-the-plots-of-popular-beers-show-that-many-of-the-most-popular-beers-have-a-bitterness-rating-well-above-the-national-median.-this-relationship-is-explored-further." class="section level1">
<h1>The most common ABV is about 5-5.5%, but there is a niche market for beers with higher ABV’s in the range of 6-10%. Since most people do not buy a beer because of its alcohol content, this is an interesting revelation that warrants further investigation. The plots of popular beers show that many of the most popular beers have a bitterness rating well above the national median. This relationship is explored further.</h1>
<div id="section-19" class="section level143">
<p></p>
</div>
<div id="question-7" class="section level60">
<p>Question 7</p>
<div id="section-20" class="section level143">
<p></p>
</div>
</div>
<div id="is-there-an-apparent-relationship-between-beer-bitterness-and-alcohol-content" class="section level3">
<h3>7. Is there an apparent relationship between beer bitterness and alcohol content?</h3>
</div>
</div>
<div id="this-code-creates-a-scatterplot-of-abv-vs-ibu-for-all-beers." class="section level1">
<h1>This code creates a scatterplot of ABV vs IBU for all beers.</h1>
<pre class="r"><code>dataset %&gt;% ggplot(aes(x = ABV * 100, y = IBU)) + 
  geom_point(position = &#39;jitter&#39;) + 
  stat_smooth(method = &#39;lm&#39;, se = FALSE) +
  ggtitle(&quot;Relationship Between IBU and ABV&quot;) + 
  theme(legend.position = &#39;none&#39;, plot.title = element_text(hjust = 0.5)) +
  xlab(&#39;ABV (%)&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="there-does-seem-to-be-a-general-positive-relationship-between-alcohol-content-and-bitterness-but-the-divergeance-from-the-model-at-higher-abv-levels-indicate-that-there-are-other-factors-at-play.-the-beers-were-divided-into-ipas-and-ales-and-the-relationship-was-explored-again." class="section level1">
<h1>There does seem to be a general positive relationship between alcohol content and bitterness, but the divergeance from the model at higher ABV levels indicate that there are other factors at play. The beers were divided into IPAs and ales and the relationship was explored again.</h1>
</div>
<div id="this-code-explores-the-abv-ibu-relationship-of-specific-beer-styles-ipas-and-ales-to-get-more-insights-into-the-relationship-which-appears-more-complicated-than-initially-thought.-the-two-styles-analyzed-display-different-relationships." class="section level1">
<h1>This code explores the ABV-IBU relationship of specific beer styles (IPA’s and Ales) to get more insights into the relationship, which appears more complicated than initially thought. The two styles analyzed display different relationships.</h1>
<pre class="r"><code># Create datasets for IPA&#39;s and Ales, remove any IPA&#39;s that are in ale dataset. Condense beers into 2 styles, IPA and Ale, then combine into a single dataframe
ipa_dataset = dataset %&gt;% filter(grepl(&#39;.*IPA.*&#39;, dataset$Style))
ale_dataset = dataset %&gt;% filter(grepl(&#39;.*Ale.*&#39;, dataset$Style))
ale_dataset = ale_dataset %&gt;% filter(!grepl(&#39;.*IPA.*&#39;, ale_dataset$Style))
ipa_dataset$Style = c(&#39;IPA&#39;)
ale_dataset$Style = c(&#39;Ale&#39;)
ipa_ale_dataset = rbind(ipa_dataset, ale_dataset)

ipa_ale_dataset %&gt;% ggplot(aes(x = ABV * 100, y = IBU, color = Style)) + 
  geom_point(position = &#39;jitter&#39;) + 
  ggtitle(&#39;Alcohol Content vs Bitterness&#39;) + 
  scale_color_manual(values = c(&#39;red&#39;, &#39;blue&#39;)) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  stat_smooth(method = &#39;lm&#39;, se = FALSE) + 
  xlab(&#39;ABV (%)&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="when-the-beers-were-divided-into-ipas-and-ales-different-relationships-were-noticed.-while-they-both-are-positive-they-are-different-enough-to-indicate-that-they-may-not-be-directly-correlated-and-that-beer-style-may-determine-the-relationship-between-abv-and-ibu." class="section level1">
<h1>When the beers were divided into IPAs and ales different relationships were noticed. While they both are positive, they are different enough to indicate that they may not be directly correlated, and that beer style may determine the relationship between ABV and IBU.</h1>
<div id="section-21" class="section level143">
<p></p>
</div>
<div id="question-8" class="section level60">
<p>Question 8</p>
<div id="section-22" class="section level143">
<p></p>
</div>
</div>
<div id="investigate-the-difference-with-respect-to-ibu-and-abv-between-ipas-and-all-other-ales-excluding-ipas.-use-knn.-may-supplement-with-other-approaches." class="section level4">
<h4>8. Investigate the difference with respect to IBU and ABV between IPAs and all other Ales (excluding IPA’s). Use KNN. May supplement with other approaches.</h4>
</div>
</div>
<div id="this-code-creates-a-subset-of-the-data-containing-only-ipas-and-all-other-ales-combined-in-a-common-ale-group-then-splits-this-subset-into-a-training-set-and-a-test-set." class="section level1">
<h1>This code creates a subset of the data containing only IPA’s and all other Ales combined in a common ‘Ale’ group, then splits this subset into a training set and a test set.</h1>
<pre class="r"><code># Filter into two groups: IPA and Ale
ipa_dataset = dataset %&gt;% filter(grepl(&#39;.*IPA.*&#39;, dataset$Style))
ale_dataset = dataset %&gt;% filter(grepl(&#39;.*Ale.*&#39;, dataset$Style))
ale_dataset = ale_dataset %&gt;% filter(!grepl(&#39;.*IPA.*&#39;, ale_dataset$Style))
ipa_dataset$Style = c(&#39;IPA&#39;)
ale_dataset$Style = c(&#39;Ale&#39;)
ipa_ale_dataset = rbind(ipa_dataset, ale_dataset)

splitpercent = .70
trainIndices = sample(1:dim(ipa_ale_dataset)[1], round(splitpercent * dim(ipa_ale_dataset)[1]))
train = ipa_ale_dataset[trainIndices,]
test = ipa_ale_dataset[-trainIndices,]</code></pre>
</div>
<div id="this-code-iterates-through-multiple-dataset-samples-and-k-values-to-estimate-the-optimum-k-value-k-5.-this-will-allow-us-to-fit-the-best-possible-model-for-the-given-data." class="section level1">
<h1>This code iterates through multiple dataset samples and k-values to estimate the optimum K-value (k = 5). This will allow us to fit the best possible model for the given data.</h1>
<pre class="r"><code>iterations = 100
numks = 30
masteracc = matrix(nrow = iterations, ncol = numks)
splitpercent = .70
for(j in 1:iterations)
{ 
  accs = data.frame(accuracy = numeric(numks), k = numeric(numks))
  trainIndices = sample(1:dim(ipa_ale_dataset)[1], round(splitpercent * dim(ipa_ale_dataset)[1]))
  train = ipa_ale_dataset[trainIndices,]
  test = ipa_ale_dataset[-trainIndices,]
    
  for (i in 1:numks)
    {
    classifications = knn(train[,c(7,8)],test[,c(7,8)],train$Style, prob = TRUE, k = i)
    tab = table(classifications,test$Style)
    CM = confusionMatrix(tab)
    masteracc[j,i] = CM$overall[1]
  }
}
MeanAcc = colMeans(masteracc)
plot(seq(1,numks,1), MeanAcc, type = &#39;l&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="this-code-runs-the-classifier-model-and-outputs-the-performance-metrics-of-the-model.-the-model-selected-was-the-k-nn-model-with-k-5.-the-model-selects-the-5-closest-beers-in-terms-of-abv-and-ibu-to-each-beer-in-the-test-set-and-assigns-the-majority-style-to-the-beer-in-question." class="section level1">
<h1>This code runs the classifier model and outputs the performance metrics of the model. The model selected was the K-NN model with k = 5. The model selects the 5 closest beers, in terms of ABV and IBU, to each beer in the test set, and assigns the majority style to the beer in question.</h1>
<pre class="r"><code>classifications = knn(train[,c(7,8)],test[,c(7,8)],train$Style, prob = TRUE, k = 5)
CM = confusionMatrix(table(test$Style,classifications))
CM</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##      classifications
##       Ale IPA
##   Ale 266  16
##   IPA  20 158
##                                           
##                Accuracy : 0.9217          
##                  95% CI : (0.8933, 0.9446)
##     No Information Rate : 0.6217          
##     P-Value [Acc &gt; NIR] : &lt;2e-16          
##                                           
##                   Kappa : 0.8344          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.6171          
##                                           
##             Sensitivity : 0.9301          
##             Specificity : 0.9080          
##          Pos Pred Value : 0.9433          
##          Neg Pred Value : 0.8876          
##              Prevalence : 0.6217          
##          Detection Rate : 0.5783          
##    Detection Prevalence : 0.6130          
##       Balanced Accuracy : 0.9191          
##                                           
##        &#39;Positive&#39; Class : Ale             
## </code></pre>
</div>
<div id="this-model-had-a-very-high-accuracy-of-90-but-it-may-not-be-the-best-model.-we-decided-to-try-a-leave-one-out-cross-validation-model-to-get-better-results." class="section level1">
<h1>This model had a very high accuracy of ~ 90%, but it may not be the best model. We decided to try a leave-one out cross validation model to get better results.</h1>
</div>
<div id="this-code-runs-a-leave-one-out-cross-validation-model-over-multiple-data-samples-and-k-values-to-determine-the-optimum-k-k-5-is-optimum.-this-model-is-similar-to-the-previous-one-but-utilizes-the-entire-dataset-to-train-instead-of-70-of-the-data." class="section level1">
<h1>This code runs a Leave one out cross validation model over multiple data samples and k-values to determine the optimum K (k = 5 is optimum). This model is similar to the previous one, but utilizes the entire dataset to train instead of 70% of the data.</h1>
<pre class="r"><code>accs = data.frame(accuracy = numeric(90), k = numeric(90))

for (i in 1:90)
{
  classifications = knn.cv(ipa_ale_dataset[,c(7,8)], ipa_ale_dataset$Style, prob = TRUE, k = i)
  CM = confusionMatrix(table(classifications, ipa_ale_dataset$Style))
  accs$accuracy[i] = CM$overal[1]
  accs$k[i] = i
}

plot(accs$k, accs$accuracy, type = &#39;l&#39;, xlab = &#39;k&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
<div id="now-we-run-our-model-to-determine-the-performance-metrics-for-the-new-model.-this-model-achieves-slightly-better-accuracy-than-the-previous-model-since-it-uses-more-data-to-train-the-model." class="section level1">
<h1>Now we run our model to determine the performance metrics for the new model. This model achieves slightly better accuracy than the previous model, since it uses more data to train the model.</h1>
<pre class="r"><code>classifications = knn.cv(ipa_ale_dataset[,c(7,8)], ipa_ale_dataset$Style, prob = TRUE, k = 5)
CM = confusionMatrix(table(classifications, ipa_ale_dataset$Style))
CM</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##                
## classifications Ale IPA
##             Ale 894  65
##             IPA  69 506
##                                           
##                Accuracy : 0.9126          
##                  95% CI : (0.8974, 0.9263)
##     No Information Rate : 0.6278          
##     P-Value [Acc &gt; NIR] : &lt;2e-16          
##                                           
##                   Kappa : 0.8134          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.7955          
##                                           
##             Sensitivity : 0.9283          
##             Specificity : 0.8862          
##          Pos Pred Value : 0.9322          
##          Neg Pred Value : 0.8800          
##              Prevalence : 0.6278          
##          Detection Rate : 0.5828          
##    Detection Prevalence : 0.6252          
##       Balanced Accuracy : 0.9073          
##                                           
##        &#39;Positive&#39; Class : Ale             
## </code></pre>
</div>
<div id="this-model-performed-slightly-better-than-the-previous-with-an-accuracy-consistently-above-90.-the-results-of-this-model-can-now-be-visualized-to-gain-insights-from-the-data." class="section level1">
<h1>This model performed slightly better than the previous, with an accuracy consistently above 90%. The results of this model can now be visualized to gain insights from the data.</h1>
</div>
<div id="this-creates-a-dataframe-that-stores-the-performance-metrics-of-our-knn-model-to-be-used-to-analyze-the-results.-it-includes-the-model-classifications-probabilities-the-beers-true-style-abv-and-ibu." class="section level1">
<h1>This creates a dataframe that stores the performance metrics of our KNN model, to be used to analyze the results. It includes the model classifications, probabilities, the beer’s true style, ABV, and IBU.</h1>
<pre class="r"><code>class_df = data.frame(&#39;classification&#39; = classifications)
probability = attributes(classifications)[3][1]
probability = unlist(probability[1])
for (var in probability){
  attr(probability, &#39;names&#39;) &lt;- NULL
}
class_df = cbind(class_df, probability)
class_df = cbind(ipa_ale_dataset$Style, class_df, ipa_ale_dataset$ABV, ipa_ale_dataset$IBU)
names(class_df) = c(&#39;Truth&#39;, &#39;Classification&#39;, &#39;Probability&#39;, &#39;ABV&#39;, &#39;IBU&#39;)
class_df$Correct = ifelse(class_df$Truth == class_df$Classification, &#39;Correct Prediction&#39;, &#39;Incorrect Prediction&#39;)
class_df$Correct = ordered(class_df$Correct, levels = c(&quot;Incorrect Prediction&quot;, &quot;Correct Prediction&quot;))
class_df$Numeric = ifelse(class_df$Truth == &#39;IPA&#39;, 1, 0)
class_df$AleProb = ifelse(class_df$Classification == &#39;Ale&#39;, class_df$Probability, 1 - class_df$Probability)</code></pre>
</div>
<div id="create-a-3d-plot-comparing-abv-and-ibu-to-the-probability-of-being-an-ale-colored-by-the-models-prediction-accuracy.-this-demonstrates-that-the-probability-of-being-an-ale-is-not-affected-by-abv-but-shows-a-significant-visual-correlation-between-ibu-and-probability-of-being-an-ale.-the-model-errors-are-fairly-evenly-distributed-across-ibu-and-abv-indicating-a-complex-relationship-that-is-not-fully-captured-by-these-two-variables." class="section level1">
<h1>Create a 3D plot Comparing ABV and IBU to the probability of being an Ale colored by the models prediction accuracy. This demonstrates that the probability of being an Ale is not affected by ABV, but shows a significant visual correlation between IBU and probability of being an Ale. The model errors are fairly evenly distributed across IBU and ABV indicating a complex relationship that is not fully captured by these two variables.</h1>
<pre class="r"><code>library(plotly)</code></pre>
<pre><code>## 
## Attaching package: &#39;plotly&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:plyr&#39;:
## 
##     arrange, mutate, rename, summarise</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     last_plot</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     layout</code></pre>
<pre class="r"><code>class_df$`Ale Probability`= class_df$AleProb * 100

model_plot &lt;- plot_ly(class_df, x = ~ABV, y = ~IBU, z = ~`Ale Probability`, color = ~Correct, colors = &#39;Set1&#39;)
model_plot &lt;- model_plot %&gt;% add_markers()
model_plot &lt;- model_plot %&gt;% layout(title = &#39;Predicted Style By ABV and IBU&#39;, scene = list(xaxis = list(title = &#39;ABV&#39;),
                                  yaxis = list(title = &#39;IBU&#39;),
                                  zaxis = list(title = &#39;Probability of Being an Ale (%)&#39;)))
model_plot</code></pre>
<div id="htmlwidget-c589a73db365d7bc72a4" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-c589a73db365d7bc72a4">{"x":{"visdat":{"24dc25ee6b98":["function () ","plotlyVisDat"]},"cur_data":"24dc25ee6b98","attrs":{"24dc25ee6b98":{"x":{},"y":{},"z":{},"color":{},"colors":"Set1","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d","mode":"markers","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Predicted Style By ABV and IBU","scene":{"xaxis":{"title":"ABV"},"yaxis":{"title":"IBU"},"zaxis":{"title":"Probability of Being an Ale (%)"}},"hovermode":"closest","showlegend":true},"source":"A","config":{"showSendToCloud":false},"data":[{"x":[0.08,0.06,0.076,0.075,0.08,0.08,0.063,0.097,0.077,0.071,0.05,0.071,0.07,0.062,0.062,0.05,0.055,0.053,0.093,0.065,0.093,0.06,0.065,0.097,0.067,0.048,0.07,0.058,0.072,0.06,0.085,0.06,0.064,0.099,0.068,0.072,0.075,0.064,0.063,0.091,0.0713529411764706,0.064,0.064,0.075,0.07,0.069,0.065,0.068,0.085,0.091,0.065,0.07,0.07,0.062,0.06,0.05,0.099,0.07,0.07,0.07,0.065,0.059,0.063,0.08,0.075,0.075,0.055,0.045,0.05,0.05,0.062,0.062,0.065,0.068,0.063,0.072,0.064,0.099,0.064,0.065,0.091,0.067,0.05,0.075,0.045,0.064,0.07,0.099,0.072,0.083,0.044,0.063,0.096,0.083,0.068,0.065,0.065,0.062,0.097,0.072,0.073,0.075,0.082,0.085,0.083,0.075,0.075,0.075,0.08,0.059,0.07,0.07,0.071,0.085,0.05,0.075,0.065,0.063,0.072,0.07,0.066,0.066,0.06,0.062,0.065,0.065,0.065,0.072,0.072,0.085,0.063,0.069,0.099,0.065,0.07,0.072,0.07,0.052,0.075,0.068,0.092,0.089,0.0645275779376499,0.065,0.06,0.068,0.07,0.067,0.066,0.07,0.068,0.066,0.065,0.07,0.07,0.099,0.069,0.07,0.067,0.082,0.099,0.085,0.092,0.085,0.057,0.075,0.066,0.095,0.06,0.085,0.07,0.063,0.075,0.077,0.07,0.07,0.075,0.07,0.045,0.075,0.062,0.075,0.07,0.07,0.065,0.06,0.067,0.067,0.07,0.062,0.061,0.061,0.061,0.068,0.061,0.061,0.073,0.073,0.067,0.08,0.08,0.06,0.063,0.062,0.062,0.085,0.0645275779376499,0.0645275779376499,0.087,0.08,0.087,0.099,0.085,0.087,0.087,0.09,0.058,0.062,0.07,0.07,0.081,0.082,0.082,0.085,0.027,0.065,0.088,0.079,0.096,0.096,0.062,0.071,0.085,0.09,0.086,0.075,0.065,0.057,0.07,0.068,0.07,0.07,0.062,0.062,0.062,0.068,0.062,0.059,0.065,0.063,0.065,0.069,0.069,0.069,0.051,0.06,0.072,0.072,0.062,0.065,0.062,0.067,0.074,0.045,0.065,0.071,0.068,0.075,0.066,0.071,0.06,0.09,0.071,0.069,0.064,0.07,0.095,0.069,0.078,0.063,0.057,0.063,0.07,0.065,0.092,0.07,0.055,0.09,0.093,0.059,0.059,0.059,0.07,0.086,0.07,0.062,0.068,0.08,0.094,0.074,0.08,0.08,0.07,0.06,0.089,0.07,0.069,0.09,0.075,0.067,0.07,0.068,0.045,0.068,0.062,0.059,0.043,0.096,0.07,0.08,0.08,0.068,0.06,0.076,0.088,0.065,0.045,0.075,0.087,0.076,0.068,0.069,0.073,0.069,0.069,0.06,0.085,0.06,0.065,0.065,0.065,0.06,0.075,0.09,0.06,0.06,0.09,0.08,0.088,0.062,0.072,0.063,0.092,0.079,0.063,0.063,0.065,0.071,0.07,0.063,0.0645275779376499,0.072,0.097,0.067,0.073,0.069,0.066,0.07,0.06,0.052,0.052,0.072,0.067,0.062,0.062,0.065,0.061,0.048,0.06,0.075,0.059,0.056,0.064,0.08,0.099,0.042,0.072,0.095,0.077,0.07,0.085,0.055,0.072,0.072,0.067,0.082,0.082,0.082,0.068,0.07,0.07,0.07,0.07,0.097,0.07,0.078,0.078,0.045,0.068,0.07,0.084,0.062,0.082,0.068,0.062,0.07,0.065,0.096,0.0873689320388349,0.065,0.065,0.068,0.069,0.085,0.085,0.065,0.08,0.087,0.066,0.071,0.07,0.06,0.04,0.062,0.07,0.068,0.088,0.088,0.062,0.062,0.072,0.062,0.08,0.062,0.06,0.074,0.06,0.072,0.055,0.068,0.068,0.061,0.062,0.098,0.08,0.05,0.05,0.063,0.065,0.065,0.065,0.07,0.07,0.068,0.04,0.065,0.078,0.07,0.068,0.07,0.093,0.06,0.064,0.059,0.084,0.068,0.068,0.07,0.071,0.061,0.07,0.072,0.066,0.092,0.087,0.072,0.0623333333333333,0.074,0.087,0.06,0.062,0.071,0.07,0.057,0.06,0.08,0.0873689320388349,0.0645275779376499,0.065,0.065,0.0645275779376499,0.057,0.065,0.0645275779376499,0.068,0.068,0.06,0.048,0.042,0.066,0.04,0.05,0.051,0.065,0.06,0.063,0.056,0.047,0.062,0.06,0.061,0.087,0.073,0.05,0.052,0.067,0.067,0.0745,0.05,0.065,0.05,0.0611739130434783,0.085,0.09,0.06,0.055,0.06,0.06,0.062,0.067,0.059,0.062,0.082,0.065,0.098,0.073,0.092,0.09,0.09,0.062,0.059,0.068,0.052,0.055,0.058,0.055,0.048,0.05,0.045,0.05,0.051,0.058,0.054,0.05,0.06,0.055,0.068,0.068,0.065,0.055,0.065,0.09,0.099,0.083,0.09,0.053,0.056,0.053,0.054,0.058,0.056,0.054,0.09,0.08,0.07,0.054,0.052,0.049,0.051,0.052,0.09,0.05,0.051,0.055,0.055,0.06,0.055,0.05,0.055,0.055,0.055,0.06,0.069,0.052,0.045,0.055,0.064,0.043,0.053,0.08,0.081,0.08,0.051,0.048,0.055,0.068,0.044,0.044,0.052,0.05,0.056,0.05,0.048,0.052,0.06,0.047,0.052,0.08,0.052,0.049,0.047,0.047,0.054,0.077,0.06,0.068,0.075,0.076,0.075,0.058,0.067,0.065,0.057,0.055,0.054,0.045,0.049,0.049,0.047,0.055,0.05,0.06,0.055,0.055,0.045,0.05,0.067,0.051,0.051,0.05,0.057456,0.057456,0.075,0.052,0.06,0.06,0.053,0.065,0.065,0.068,0.05,0.059,0.051,0.047,0.055,0.055,0.045,0.057,0.051,0.058,0.065,0.058,0.06,0.06,0.058,0.058,0.058,0.0484105263157895,0.0545774058577406,0.057456,0.048,0.046,0.039,0.039,0.039,0.039,0.039,0.039,0.039,0.039,0.039,0.039,0.039,0.058,0.039,0.058,0.052,0.048,0.052,0.052,0.052,0.052,0.048,0.052,0.056,0.056,0.048,0.0663333333333333,0.057456,0.0545774058577406,0.0579264705882353,0.0496346153846154,0.0579264705882353,0.053,0.048,0.054,0.042,0.054,0.042,0.042,0.061,0.043,0.06,0.07,0.05,0.067,0.05,0.055,0.048,0.043,0.054,0.058,0.05,0.055,0.052,0.052,0.051,0.049,0.058,0.057,0.05,0.057,0.047,0.058,0.047,0.053,0.048,0.058,0.047,0.075,0.05,0.05,0.052,0.045,0.058,0.062,0.053,0.072,0.055,0.05,0.055,0.05,0.065,0.056,0.052,0.049,0.045,0.05,0.05,0.065,0.066,0.055,0.075,0.048,0.06,0.052,0.059,0.051,0.051,0.06,0.068,0.05,0.052,0.05,0.054,0.035,0.054,0.054,0.052,0.05,0.0528571428571429,0.052,0.05,0.058,0.058,0.05,0.059,0.059,0.053,0.052,0.055,0.048,0.063,0.055,0.05,0.055,0.055,0.052,0.055,0.048,0.041,0.052,0.049,0.042,0.05,0.042,0.06,0.056,0.051,0.092,0.051,0.087,0.061,0.054,0.057456,0.055,0.055,0.045,0.045,0.04,0.056,0.056,0.056,0.056,0.054,0.054,0.056,0.056,0.058,0.054,0.04,0.05,0.04,0.04,0.06,0.05,0.05,0.05,0.038,0.071,0.051,0.099,0.056,0.072,0.042,0.045,0.053,0.06,0.053,0.053,0.08,0.065,0.09,0.065,0.065,0.05,0.08,0.065,0.065,0.065,0.08,0.07,0.065,0.052,0.065,0.047,0.065,0.056,0.049,0.06,0.056,0.042,0.056,0.058,0.055,0.058,0.058,0.056,0.055,0.055,0.05,0.049,0.039,0.06,0.058,0.06,0.055,0.058,0.073,0.058,0.073,0.069,0.055,0.066,0.072,0.045,0.051,0.068,0.057,0.053,0.063,0.063,0.053,0.077,0.06,0.077,0.053,0.048,0.052,0.042,0.052,0.054,0.046,0.052,0.057,0.05,0.052,0.042,0.05,0.068,0.055,0.049,0.049,0.049,0.06,0.047,0.075,0.05,0.075,0.052,0.042,0.054,0.064,0.083,0.049,0.064,0.054,0.042,0.058,0.055,0.052,0.062,0.052,0.055,0.047,0.052,0.055,0.045,0.065,0.055,0.049,0.043,0.055,0.06,0.063,0.055,0.053,0.065,0.05,0.055,0.081,0.058,0.05,0.08,0.05,0.07,0.06,0.049,0.05,0.059,0.055,0.099,0.05,0.059,0.048,0.05,0.049,0.052,0.044,0.042,0.059,0.058,0.055,0.056,0.052,0.055,0.06,0.038,0.051,0.045,0.052,0.055,0.045,0.045,0.054,0.056,0.045,0.05,0.05,0.086,0.055,0.047,0.08,0.055,0.05,0.08,0.04,0.082,0.055,0.05,0.073,0.061,0.053,0.06,0.055,0.049,0.046,0.053,0.06,0.053,0.056,0.046,0.054,0.053,0.078,0.045,0.052,0.0523333333333333,0.05,0.051,0.065,0.051,0.078,0.06,0.06,0.052,0.052,0.051,0.047,0.047,0.049,0.047,0.055,0.066,0.078,0.052,0.047,0.051,0.042,0.047,0.05,0.055,0.055,0.047,0.053,0.055,0.045,0.065,0.048,0.065,0.046,0.04,0.04,0.055,0.048,0.055,0.042,0.055,0.05,0.052,0.055,0.043,0.046,0.05,0.055,0.058,0.045,0.045,0.055,0.07,0.08,0.049,0.05,0.063,0.035,0.045,0.055,0.092,0.075,0.045,0.057,0.047,0.055,0.052,0.042,0.06,0.063,0.057,0.052,0.063,0.056,0.056,0.05,0.05,0.05,0.045,0.051,0.05,0.05,0.047,0.05,0.05,0.051,0.051,0.05,0.057,0.048,0.061,0.053,0.044,0.056,0.06,0.066,0.05,0.077,0.08,0.073,0.056,0.045,0.055,0.05,0.051,0.062,0.048,0.045,0.052,0.05,0.056,0.045,0.049,0.055,0.045,0.066,0.053,0.07,0.054,0.048,0.048,0.054,0.048,0.05,0.053,0.07,0.053,0.053,0.05,0.044,0.044,0.083,0.05,0.06,0.05,0.049,0.051,0.056,0.06,0.05,0.06,0.051,0.055,0.06,0.055,0.049,0.055,0.064,0.055,0.08,0.045,0.05,0.046,0.059,0.059,0.055,0.051,0.051,0.047,0.062,0.05,0.0496346153846154,0.056,0.053,0.053,0.074,0.074,0.08,0.065,0.065,0.054,0.045,0.042,0.055,0.045,0.053,0.053,0.06,0.056,0.073,0.056,0.073,0.05,0.04,0.04,0.05,0.055,0.054,0.05,0.063,0.052,0.054,0.056,0.05,0.05,0.09,0.09,0.07,0.051,0.047,0.049,0.049,0.057,0.044,0.058,0.063,0.052,0.055,0.052,0.055,0.051,0.05,0.05,0.055,0.07,0.048,0.045,0.045,0.058,0.047,0.048,0.0545774058577406,0.053,0.052,0.055,0.053,0.065,0.056,0.059,0.037,0.05,0.05,0.05,0.05,0.05,0.058,0.056,0.05,0.048,0.052,0.059,0.048,0.046,0.058,0.05,0.058,0.05,0.065,0.056,0.045,0.06,0.06,0.07,0.05,0.0484105263157895,0.0545774058577406,0.047,0.0545774058577406,0.047,0.047,0.047,0.047,0.065,0.06,0.05,0.095,0.06,0.072,0.06,0.056,0.058,0.06,0.055,0.057,0.054,0.054,0.056,0.044,0.05,0.051,0.051,0.058,0.057456,0.044,0.07,0.054,0.0689714285714286,0.074,0.045,0.048,0.052,0.05,0.055,0.0415,0.0496346153846154,0.057456,0.044,0.055,0.052,0.065,0.08,0.065,0.065,0.08,0.065,0.065,0.08,0.035,0.04,0.05,0.04,0.047,0.065,0.055,0.065,0.05,0.052,0.058,0.054,0.048,0.056,0.054,0.064,0.068,0.056,0.08,0.045,0.053,0.045,0.0545774058577406,0.0415,0.045,0.0496346153846154,0.054,0.05,0.057,0.05,0.045,0.05,0.062,0.054,0.053,0.056,0.055,0.057456,0.05,0.05,0.072,0.042,0.06,0.056,0.043,0.049],"y":[68,65,68,85,100,100,42,93.32,67.6345514950166,67.6345514950166,67.6345514950166,67.6345514950166,67.6345514950166,67.6345514950166,57,57,57,57,93.32,57,57,67.6345514950166,57,57,74,47,51,72,65,104,115,67.6345514950166,90,115,67.6345514950166,86,77,75,75,91,57,75,75,77,61,65,67.6345514950166,70,90,99,57,85,85,80,67.6345514950166,67.6345514950166,101,75,67.6345514950166,70,67.6345514950166,67.6345514950166,69,93.32,63,60,67.6345514950166,67.6345514950166,100,67.6345514950166,48.8333333333333,67.6345514950166,70,110,60,93,62,111,62,62,103,74,67.6345514950166,75,47,67.6345514950166,70,90,67.6345514950166,93.32,44,76,85,100,67.6345514950166,67.6345514950166,67.6345514950166,99,120,67.6345514950166,69,90,68,57,93.32,67.6345514950166,67.6345514950166,57,67.6345514950166,70,82,57,75,90,62,115,67.6345514950166,69,87,67.6345514950166,75,75,60,67.6345514950166,70,70,70,65,65,69,65,70,93.32,67.6345514950166,67.6345514950166,75,67.6345514950166,67,85,66,75,126,67.6345514950166,75,70,85,70,70,72,94,67.6345514950166,72,82,100,100,100,67.6345514950166,88,60,103,100,110,100,110,58,67.6345514950166,70,85,75,100,70,64,89,65,60,60,70,60,67.6345514950166,70,65,70,60,60,67.6345514950166,67.6345514950166,70,70,60,82,94,94,94,100,60,67.6345514950166,82,83,47,93.32,93.32,70,67.6345514950166,60,60,67.6345514950166,67.6345514950166,67.6345514950166,85,93.32,85,100,67.6345514950166,85,85,60,67.6345514950166,80,80,80,93.32,93.32,80,93.32,67.6345514950166,67.6345514950166,93.32,93.32,93.32,93.32,67.6345514950166,67.6345514950166,57,93.32,93.32,67.6345514950166,67.6345514950166,54.7142857142857,73,100,68,70,70,70,70,60,70,55,90,70,90,69,69,93.32,67.6345514950166,67.6345514950166,75,75,62,77,67.6345514950166,67.6345514950166,97,67.6345514950166,67.6345514950166,67.6345514950166,75,85,54.7142857142857,60,67.6345514950166,118,69,65,66,80,104,81,80,61,70,61,80,80,115,67.6345514950166,64,130,90,42,42,42,67.6345514950166,93.32,65,61,65,70,92,74,70,70,75,60,88,54.7142857142857,69,93.32,67.6345514950166,70,67.6345514950166,65,67.6345514950166,65,72,42,67.6345514950166,93.32,67.6345514950166,120,120,90,67.6345514950166,65,77,67.6345514950166,44,51,80,73,66,67,87,69,67.6345514950166,55,85,55,75,60,60,67.6345514950166,67.6345514950166,75,48.8333333333333,48.8333333333333,75,80,108,65,60,100,93.32,93.32,100,100,72,92,70,67.6345514950166,67.6345514950166,67.6345514950166,93.32,60,85,51,67.6345514950166,67.6345514950166,54.7142857142857,67.6345514950166,67.6345514950166,100,70,65,65,69,64,67.6345514950166,64,70,135,70,95,88,93,48.8333333333333,85,99,67.6345514950166,75,85,67.6345514950166,67.6345514950166,80,67.6345514950166,100,100,100,67.6345514950166,70,70,70,65,94,70,74,74,67.6345514950166,67.6345514950166,113,90,67.6345514950166,138,68,65,80,67.6345514950166,93.32,93.32,52,52,65,65,86,86,67.6345514950166,85,85,67.6345514950166,62,67.6345514950166,67.6345514950166,67.6345514950166,67.6345514950166,70,67.6345514950166,85,85,67.6345514950166,67.6345514950166,70,67.6345514950166,86,65,54.7142857142857,60,48.8333333333333,93.32,65,47,47,66,67.6345514950166,76,95,44,44,67.6345514950166,67.6345514950166,67.6345514950166,71,67.6345514950166,75,67.6345514950166,67.6345514950166,80,67.6345514950166,70,67.6345514950166,67.6345514950166,103,64,67.6345514950166,75,82,75,70,80,85,64,105,67.6345514950166,100,85,60,67.6345514950166,54.7142857142857,83,93.32,55,65,60,67,67.6345514950166,69,57,93.32,67.6345514950166,52,67.6345514950166,67.6345514950166,67.6345514950166,70,67.6345514950166,67.6345514950166,67.6345514950166,38,19,42,21,13,20,38,27,24,30,16,19,29.8947368421053,44.9411764705882,20.6885245901639,40,28.3913043478261,44.9411764705882,44.9411764705882,29.6666666666667,29.6666666666667,29.6666666666667,23.875,29.6666666666667,68.9,23.875,72,28.3913043478261,23.875,28.3913043478261,23.875,36.2987012987013,29.6666666666667,28.3913043478261,28.3913043478261,36.2987012987013,25,28.3913043478261,29.6666666666667,27,27,28.3913043478261,28.3913043478261,29.6666666666667,25,29.8947368421053,20.6885245901639,20.3333333333333,68.9,10,15,40,29.8947368421053,27,22,44.9411764705882,37,23.875,20.3333333333333,40,16,68.9,29.8947368421053,40,20.6885245901639,30,36,23,30,23,50,20,26.9090909090909,20,50,23,30,25,29.8947368421053,23,44.9411764705882,23,20.6885245901639,18,72,18,36,45,20,20.6885245901639,20,15,45,45,44.9411764705882,20.983606557377,34,35,20.6885245901639,17,28.3913043478261,44.9411764705882,20.983606557377,24.8181818181818,36.2987012987013,36.2987012987013,26.9090909090909,44.9411764705882,40,23.875,12,22,44.9411764705882,20,20,20,20,34,48,50,34,23.875,11,35,20.983606557377,20,44.9411764705882,24.8181818181818,28.3913043478261,24,30,29.8947368421053,30,44.9411764705882,23.2,36.2987012987013,27,44.9411764705882,45,44.9411764705882,22,22,55,23.2,36.2987012987013,36.2987012987013,29.8947368421053,68.9,18,28,33,45,45,20,36.2987012987013,36.2987012987013,25,25,44.9411764705882,46,44.9411764705882,28.3913043478261,33,36.2987012987013,20.983606557377,36.2987012987013,17,19,45,44.9411764705882,8,44.9411764705882,36,43,44.9411764705882,43,34,68.9,20.6885245901639,20.6885245901639,29.8947368421053,20.6885245901639,44.9411764705882,36.2987012987013,16,20,20,20,20,20,20,20,20,20,20,20,20,60,20,60,44.9411764705882,20.6885245901639,20.6885245901639,18,18,18,20.6885245901639,18,37,37,26,26.9090909090909,36.2987012987013,44.9411764705882,29.8947368421053,20.983606557377,29.8947368421053,36.2987012987013,11,30,18,30,18,20,36.2987012987013,18,30,32,40,23.2,36.2987012987013,42,25,45,20,29.8947368421053,23.875,36.2987012987013,24,24,36.2987012987013,20.983606557377,45,40,28,36,20.983606557377,29.8947368421053,20.983606557377,45,20.983606557377,44.9411764705882,20.983606557377,22,25,40,21,16,35,33,36,40,28.3913043478261,20,28.3913043478261,20,65,20.6885245901639,42,20.983606557377,6,35,25,25,20,40,33,25,44.9411764705882,23,31.4,21,21,50,68.9,7,9,7,33,20.983606557377,32,33,7,7,20.3333333333333,36.2987012987013,20,60,60,20,14,14,49,36.2987012987013,42,32,44.9411764705882,29.8947368421053,44.9411764705882,25,25,20.6885245901639,44.9411764705882,18,20.3333333333333,44.9411764705882,29.8947368421053,24,22,24,24.8181818181818,31.4,44.9411764705882,72,44.9411764705882,29,30,24,36.2987012987013,20.983606557377,37,18,28,18,55,55,55,55,24,24,55,55,36.2987012987013,44.9411764705882,29,10,17,34,21,20,28.3913043478261,35,20.3333333333333,36,44.9411764705882,25,40,68.9,26,36,22,25,22,22,25,65,29.6666666666667,65,65,23.2,24.2307692307692,65,65,65,35,29.8947368421053,65,44.9411764705882,65,22,44.9411764705882,44.9411764705882,25,24.8181818181818,4,44.9411764705882,4,15,28,15,15,4,44.9411764705882,44.9411764705882,44.9411764705882,20.983606557377,22,36.2987012987013,28,44.9411764705882,20.6885245901639,44.9411764705882,44.9411764705882,60,28.3913043478261,28.3913043478261,44.9411764705882,44.9411764705882,28.3913043478261,44.9411764705882,45,21,20,25,35,35,25,40,53,40,20,35,21,44.9411764705882,27,20,20.6885245901639,27,36,22,32,20.6885245901639,44.9411764705882,23.875,40,20,20,20,50,20.6885245901639,53,26.9090909090909,53,23,22,42,29.8947368421053,42.7398431931575,20.983606557377,29.8947368421053,44.9411764705882,20.6885245901639,44.9411764705882,44.9411764705882,23.875,68.9,40,30,46,50,20.3333333333333,20.983606557377,36.2987012987013,29.8947368421053,21,21,35,40,23,35,28.3913043478261,28.3913043478261,12,36.2987012987013,17,38,24,24.2307692307692,15,23.875,44.9411764705882,15,26,36.2987012987013,30,43,50,20,10,36.2987012987013,20.983606557377,26,45,35,28.3913043478261,35,20,30,50,20,30,18,31,35,18,30,23.2,20.983606557377,29.8947368421053,36.2987012987013,28.3913043478261,68.9,68.9,72,44.9411764705882,20.983606557377,72,44.9411764705882,22,28.3913043478261,39,36.2987012987013,55,23.875,23.875,44.9411764705882,20.983606557377,30,35,10,30,40,27,22,28,27,45,20,28.3913043478261,20.983606557377,36.2987012987013,27.6,16,24,20,24,16,43,23.2,20,40,36.2987012987013,44.9411764705882,20.6885245901639,28,20.6885245901639,35,44,34,20,20.6885245901639,17,25,28,12,31.4,31.4,20.6885245901639,7,44.9411764705882,20.6885245901639,20.983606557377,20.6885245901639,65,20,44.9411764705882,44.9411764705882,36.2987012987013,35,25,35,28,21,32,28.3913043478261,20.983606557377,12,44.9411764705882,37,39,18,18,20,68.9,26.9090909090909,20.983606557377,44.9411764705882,44.9411764705882,45,44.9411764705882,60,25,31,31.4,31,14,20.6885245901639,44.9411764705882,20.983606557377,29.8947368421053,50,46,16,37,20.3333333333333,20.3333333333333,44.9411764705882,20.983606557377,32,19,26,35,40,20.983606557377,35,40,26,26,35,29,15,11,27.6,18,55,25,44,44.9411764705882,36.2987012987013,72,36.2987012987013,44.9411764705882,21,24.8181818181818,18,31,17,23,24.8181818181818,27,29.8947368421053,41,24.8181818181818,20,60,32,30,48,22,30,20.983606557377,25,30,20.983606557377,30,48,22,10,14,35,42,42,35,24.8181818181818,44.9411764705882,24.8181818181818,36.2987012987013,40,44.9411764705882,35,28.3913043478261,24,20,15,29.8947368421053,20.3333333333333,22,20.983606557377,28.3913043478261,29.8947368421053,36.2987012987013,44.9411764705882,20.6885245901639,35,60,60,44.9411764705882,20.983606557377,20.6885245901639,24.8181818181818,36.2987012987013,20.983606557377,20.983606557377,44.9411764705882,20.983606557377,20.983606557377,68.9,68.9,35,65,65,19,15,9,30,28,30,16,50,35,55,35,55,11,20.6885245901639,29.8947368421053,44.9411764705882,29.8947368421053,44.9411764705882,20,44.9411764705882,29.8947368421053,20.983606557377,36.2987012987013,36.2987012987013,36.2987012987013,23.875,23.875,68.9,44.9411764705882,17,35,35,35,13,20,30,36.2987012987013,24.8181818181818,36.2987012987013,40,20,30,45,28,24,28.3913043478261,16,16,36.2987012987013,44.9411764705882,28,44.9411764705882,48,23,24.8181818181818,43,44.9411764705882,35,18,53,28.3913043478261,19,19,20.983606557377,36.2987012987013,46,46,40,20.983606557377,44.9411764705882,15,16,20,26.9090909090909,15,26.9090909090909,36.2987012987013,35,30,44.9411764705882,20.983606557377,18,29.8947368421053,30,20.6885245901639,44.9411764705882,42,44.9411764705882,20.6885245901639,20.6885245901639,20.6885245901639,20.6885245901639,26,29,45,19,31,55,28.3913043478261,36,36,20.3333333333333,44.9411764705882,29.8947368421053,30,30,21,38,44.9411764705882,32,31,27,36.2987012987013,16,68.9,27,68.9,12,20.983606557377,20.3333333333333,17,15,44.9411764705882,22,20.983606557377,36.2987012987013,22,36.2987012987013,29.8947368421053,65,35,65,65,35,65,65,35,20.983606557377,20.983606557377,20.983606557377,9,36.2987012987013,11,50,11,31.4,44.9411764705882,44.9411764705882,29.8947368421053,20.983606557377,36,23.2,23.875,29.8947368421053,27,25,20,28,20.6885245901639,44.9411764705882,22,36.2987012987013,20.983606557377,36.2987012987013,20.6885245901639,26.9090909090909,36.2987012987013,18,44.9411764705882,17,44.9411764705882,22,44.9411764705882,23.2,36.2987012987013,36.2987012987013,20.983606557377,44.9411764705882,29.8947368421053,36.2987012987013,36.2987012987013,44.9411764705882,31.4],"z":[40,0,40,20,0,0,33.3333333333333,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.1111111111111,33.3333333333333,11.1111111111111,20,0,0,20,0,16.6666666666667,20,0,11.1111111111111,40,0,0,14.2857142857143,0,0,0,40,10,20,0,0,20,11.1111111111111,0,28.5714285714286,28.5714285714286,40,0,0,20,11.1111111111111,0,8.33333333333334,0,0,0,0,0,33.3333333333333,0,0,0,0,20,0,0,0,16.6666666666667,16.6666666666667,0,0,0,0,0,11.1111111111111,0,20,33.3333333333333,0,8.33333333333334,20,0,0,40,0,33.3333333333333,0,0,0,0,0,12.5,0,0,14.2857142857143,40,0,0,0,0,0,0,0,12.5,0,12.5,20,0,20,0,0,0,0,11.1111111111111,11.1111111111111,44.4444444444444,0,0,0,0,0,0,14.2857142857143,0,6.66666666666667,0,0,0,12.5,0,0,20,40,14.2857142857143,0,0,0,0,20,8.33333333333334,0,20,0,0,20,12.5,0,0,20,0,0,0,0,20,0,20,0,12.5,0,0,33.3333333333333,16.6666666666667,0,8.33333333333334,16.6666666666667,11.1111111111111,20,0,0,40,0,0,40,0,40,0,0,0,0,0,0,0,12.5,0,0,0,0,33.3333333333333,0,12.5,14.2857142857143,40,0,0,0,0,28.5714285714286,28.5714285714286,0,0,0,0,0,0,20,0,0,0,33.3333333333333,0,40,0,0,0,0,40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.1111111111111,0,33.3333333333333,8.33333333333334,0,0,0,0,0,33.3333333333333,16.6666666666667,0,16.6666666666667,0,0,0,0,0,12.5,12.5,0,20,0,0,16.6666666666667,0,0,0,12.5,20,0,11.1111111111111,0,12.5,0,20,40,0,0,0,40,11.1111111111111,0,11.1111111111111,0,40,20,0,20,0,20,40,40,40,0,0,0,11.1111111111111,40,14.2857142857143,20,0,14.2857142857143,14.2857142857143,11.1111111111111,44.4444444444444,0,0,0,0,0,0,0,40,0,40,20,40,0,0,0,12.5,12.5,16.6666666666667,0,14.2857142857143,33.3333333333333,0,40,11.1111111111111,40,33.3333333333333,40,0,0,0,0,40,0,40,0,0,0,0,0,14.2857142857143,20,20,14.2857142857143,40,0,0,11.1111111111111,0,0,0,0,0,20,20,8.33333333333334,0,0,0,0,0,16.6666666666667,11.1111111111111,0,0,0,0,0,0,0,0,0,0,16.6666666666667,0,16.6666666666667,40,0,0,16.6666666666667,0,11.1111111111111,20,20,12.5,0,11.1111111111111,0,0,0,0,0,0,0,0,0,8.33333333333334,8.33333333333334,8.33333333333334,0,0,8.33333333333334,0,0,0,0,16.6666666666667,20,0,0,40,0,0,0,0,0,44.4444444444444,44.4444444444444,40,20,0,0,0,0,0,0,0,0,0,0,0,8.33333333333334,0,0,0,0,0,20,0,0,0,0,20,20,0,0,40,40,40,0,0,14.2857142857143,40,40,0,0,0,22.2222222222222,0,11.1111111111111,0,0,40,0,8.33333333333334,0,0,0,16.6666666666667,0,16.6666666666667,14.2857142857143,12.5,0,0,20,16.6666666666667,0,0,0,0,33.3333333333333,0,0,14.2857142857143,0,40,0,11.1111111111111,0,0,0,0,0,0,44.4444444444444,0,0,0,0,0,0,0,88.8888888888889,100,60,100,100,100,88.8888888888889,100,100,100,100,100,100,100,100,66.6666666666667,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,71.4285714285714,100,100,100,71.4285714285714,100,80,80,100,80,100,77.7777777777778,100,100,100,77.7777777777778,100,80,100,100,100,100,100,100,100,100,100,100,60,100,100,100,100,60,60,100,100,100,85.7142857142857,100,100,100,100,100,100,100,100,100,100,71.4285714285714,100,100,100,100,100,100,100,100,100,60,60,100,100,100,83.3333333333333,100,100,100,100,100,100,80,100,80,100,100,100,100,100,75,100,100,100,72.7272727272727,100,100,100,100,100,100,100,83.3333333333333,80,80,100,100,100,100,100,100,80,100,100,83.3333333333333,100,100,100,100,100,60,100,100,100,100,80,100,80,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,66.6666666666667,100,66.6666666666667,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,60,100,100,100,100,100,100,100,100,57.1428571428571,77.7777777777778,100,80,100,100,100,81.8181818181818,100,100,100,100,100,100,100,100,100,80,100,60,100,100,100,100,69.5652173913043,100,85.7142857142857,100,100,83.3333333333333,100,100,100,71.4285714285714,83.3333333333333,100,100,100,100,100,100,71.4285714285714,100,100,100,100,80,100,100,80,100,100,100,100,100,66.6666666666667,66.6666666666667,100,100,100,50,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,85.7142857142857,85.7142857142857,85.7142857142857,85.7142857142857,100,100,85.7142857142857,85.7142857142857,100,100,100,100,100,100,100,100,100,83.3333333333333,100,83.3333333333333,100,100,77.7777777777778,100,100,100,100,100,100,100,100,69.5652173913043,100,69.5652173913043,69.5652173913043,100,100,69.5652173913043,69.5652173913043,69.5652173913043,100,100,69.5652173913043,100,69.5652173913043,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,66.6666666666667,100,100,100,100,100,100,80,100,100,100,100,100,100,66.6666666666667,66.6666666666667,66.6666666666667,100,66.6666666666667,100,100,100,100,100,100,80,100,100,100,100,100,71.4285714285714,100,100,100,71.4285714285714,100,62.5,100,62.5,100,100,100,100,80,100,100,100,100,100,100,100,100,100,100,80,83.3333333333333,100,100,100,100,100,100,100,72.7272727272727,100,100,100,100,100,100,100,88.8888888888889,100,100,100,100,100,100,100,100,100,80,66.6666666666667,100,100,100,100,100,60,60,100,100,100,100,83.3333333333333,100,100,100,100,71.4285714285714,100,100,100,100,100,100,100,100,100,100,100,100,83.3333333333333,100,100,100,70,100,87.5,100,100,100,100,100,100,100,60,81.8181818181818,100,100,100,100,75,100,100,100,100,100,100,100,100,100,100,80,100,100,100,100,100,100,100,100,100,60,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,69.5652173913043,100,100,100,100,66.6666666666667,100,60,100,100,100,100,100,100,100,100,72.7272727272727,100,100,100,100,100,100,100,100,66.6666666666667,100,100,100,100,100,100,100,100,100,100,100,60,80,100,100,100,100,100,100,100,100,100,83.3333333333333,100,100,83.3333333333333,100,100,100,83.3333333333333,100,100,100,100,100,85.7142857142857,100,60,100,100,83.3333333333333,100,100,100,100,100,100,100,100,100,100,100,81.25,100,100,100,100,100,60,100,100,100,100,100,100,100,60,100,100,100,83.3333333333333,60,60,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,75,60,60,100,100,100,100,100,100,100,100,100,100,100,100,100,69.5652173913043,69.5652173913043,100,100,100,100,100,100,100,71.4285714285714,100,66.6666666666667,100,66.6666666666667,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,83.3333333333333,83.3333333333333,100,100,100,100,100,100,100,71.4285714285714,100,100,80,100,100,100,100,100,100,100,100,100,60,100,100,80,100,100,100,100,100,100,100,100,100,80,80,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,80,100,100,100,100,100,100,100,80,100,100,66.6666666666667,100,80,80,100,100,100,100,100,100,62.5,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,69.5652173913043,100,69.5652173913043,69.5652173913043,100,69.5652173913043,69.5652173913043,100,100,100,100,100,100,100,80,100,100,100,100,100,100,80,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100],"type":"scatter3d","mode":"markers","name":"Correct Prediction","marker":{"color":"rgba(55,126,184,1)","line":{"color":"rgba(55,126,184,1)"}},"textfont":{"color":"rgba(55,126,184,1)"},"error_y":{"color":"rgba(55,126,184,1)"},"error_x":{"color":"rgba(55,126,184,1)"},"line":{"color":"rgba(55,126,184,1)"},"frame":null},{"x":[0.045,0.065,0.05,0.047,0.058,0.07,0.05,0.038,0.065,0.055,0.062,0.047,0.045,0.075,0.065,0.04,0.075,0.04,0.049,0.043,0.048,0.048,0.041,0.056,0.077,0.045,0.048,0.042,0.072,0.062,0.059,0.059,0.059,0.065,0.07,0.055,0.06,0.055,0.055,0.042,0.04,0.056,0.04,0.058,0.065,0.05,0.046,0.065,0.058,0.062,0.062,0.067,0.045,0.07,0.066,0.073,0.062,0.072,0.065,0.065,0.06,0.065,0.065,0.065,0.068,0.085,0.055,0.058,0.09,0.0765384615384615,0.07,0.059,0.099,0.07,0.073,0.073,0.06,0.057,0.075,0.048,0.058,0.065,0.065,0.099,0.08,0.057,0.072,0.082,0.057,0.057,0.067,0.08,0.07,0.061,0.06,0.065,0.078,0.065,0.067,0.067,0.099,0.063,0.08,0.08,0.05,0.052,0.065,0.071,0.057,0.084,0.072,0.095,0.075,0.061,0.085,0.068,0.07,0.076,0.06,0.06,0.071,0.062,0.06,0.068,0.082,0.063,0.065,0.08,0.058,0.077,0.062,0.073,0.055,0.06],"y":[50,65,35,42,36,46,45,40,33,45,68,35,40,35,65,55,72,42,35,60,48,48,41,55,30,50,38,35,50,45,60,60,60,65,40,40,50,45,40,30,37,50,37,45,45,55,45,65,55,68,43,45,30,45,50,50,55,45,44,44,40,65,65,65,55,50,64,58,50,65.4166666666667,70,47,85,68,70,70,60,42,93,44,44,45,45,85,80,68,75,65,47,44,71,70,68,60,55,80,60,115,75,85,100,55,69,80,61,49,80,83,42,90,60,49,77,41,52,65,72,78,54,54,95,55,75,65,65.4166666666667,42,45,54,49,71,42,85,52,55],"z":[80,73.9130434782609,100,100,100,100,100,85.7142857142857,100,80,50,87.5,100,100,73.9130434782609,81.8181818181818,60,80,91.6666666666667,100,80,80,55.5555555555556,100,100,80,77.7777777777778,80,57.1428571428571,66.6666666666667,70,70,70,73.9130434782609,80,85.7142857142857,85.7142857142857,80,85.7142857142857,80,83.3333333333333,88.8888888888889,83.3333333333333,71.4285714285714,60,90,80,73.9130434782609,54.5454545454545,50,100,60,80,50,66.6666666666667,62.5,57.1428571428571,50,80,80,81.8181818181818,73.9130434782609,73.9130434782609,73.9130434782609,83.3333333333333,40,0,0,40,28.5714285714286,0,20,16.6666666666667,16.6666666666667,16.6666666666667,16.6666666666667,33.3333333333333,42.8571428571429,0,20,42.8571428571429,40,40,16.6666666666667,20,33.3333333333333,0,0,20,20,11.1111111111111,0,16.6666666666667,16.6666666666667,20,20,16.6666666666667,0,0,0,0,42.8571428571429,0,20,33.3333333333333,50,20,0,42.8571428571429,0,0,42.8571428571429,20,30,42.8571428571429,20,0,20,28.5714285714286,28.5714285714286,0,42.8571428571429,0,20,28.5714285714286,16.6666666666667,40,40,50,11.1111111111111,16.6666666666667,0,40,20],"type":"scatter3d","mode":"markers","name":"Incorrect Prediction","marker":{"color":"rgba(228,26,28,1)","line":{"color":"rgba(228,26,28,1)"}},"textfont":{"color":"rgba(228,26,28,1)"},"error_y":{"color":"rgba(228,26,28,1)"},"error_x":{"color":"rgba(228,26,28,1)"},"line":{"color":"rgba(228,26,28,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
<div id="the-probability-of-being-an-ale-decreases-as-the-the-ibu-rating-increases-indicating-correlation.-no-such-correlation-exists-with-abv.-this-same-information-is-plotted-below-in-2-dimensions-for-clarity." class="section level1">
<h1>The probability of being an ale decreases as the the IBU rating increases indicating correlation. No such correlation exists with ABV. This same information is plotted below in 2 dimensions for clarity.</h1>
</div>
<div id="create-2d-scatterplots-of-probability-of-being-an-ale-vs-abv-and-probability-of-being-an-ale-vs-ibu-colored-by-the-beers-style-this-is-the-same-informtion-shown-in-the-3d-plot-above.-this-is-a-simplified-view-that-confirms-that-ibu-and-the-probability-of-being-an-ale-are-correlated-while-abv-and-probability-of-being-an-ale-are-not." class="section level1">
<h1>Create 2D scatterplots of probability of being an ale vs ABV and probability of being an ale vs IBU colored by the beer’s style (this is the same informtion shown in the 3D plot above). This is a simplified view that confirms that IBU and the probability of being an ale are correlated, while ABV and probability of being an ale are not.</h1>
<pre class="r"><code>class_df$`Ale Probability` = class_df$AleProb * 100

class_df %&gt;% ggplot(aes(x = ABV * 100, y = `Ale Probability`, color = Truth)) + 
  geom_point(position = &#39;jitter&#39;) + 
  ggtitle(&#39;Predicted Style Probabilities (ABV)&#39;) + 
  scale_color_manual(&#39;True Style&#39;, values = c(&#39;red&#39;, &#39;blue&#39;)) + 
  ylab(&#39;Probability of Being an Ale (%)&#39;) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab(&#39;ABV (%)&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre class="r"><code>class_df %&gt;% ggplot(aes(x = IBU, y = `Ale Probability`, color = Truth)) + 
  geom_point(position = &#39;jitter&#39;) + 
  ggtitle(&#39;Predicted Style Probabilities (IBU)&#39;) + 
  scale_color_manual(&#39;True Style&#39;, values = c(&#39;red&#39;, &#39;blue&#39;)) + 
  ylab(&#39;Probability of Being an Ale (%)&#39;) + 
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-23-2.png" width="672" /></p>
</div>
<div id="create-a-2d-plot-of-abv-vs-ibu-colored-by-model-correctness.-this-shows-that-most-errors-occur-in-a-middle-ibu-range-of-45-75-indicating-that-this-range-may-be-thought-of-as-a-boundary-between-ipas-and-ales." class="section level1">
<h1>Create a 2D plot of ABV vs IBU colored by model correctness. This shows that most errors occur in a middle IBU range of ~45-75, indicating that this range may be thought of as a boundary between IPA’s and ales.</h1>
<pre class="r"><code>class_df %&gt;% ggplot(aes(x = IBU, y = ABV * 100, color = Correct)) + 
  geom_point(position = &#39;jitter&#39;) + 
  ggtitle(&#39;KNN Model Performance&#39;) +
  scale_color_manual(&#39;Model Performance&#39;, values = c(&#39;red&#39;, &#39;blue&#39;)) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab(&#39;ABV (%)&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
<div id="a-logistic-regression-classifier-was-trained-in-order-to-determine-the-statistical-significance-of-the-relationships-between-beer-style-and-ibu-and-abv" class="section level1">
<h1>A logistic regression classifier was trained in order to determine the statistical significance of the relationships between beer style and IBU and ABV</h1>
</div>
<div id="create-training-and-test-sets" class="section level1">
<h1>Create training and test sets</h1>
<pre class="r"><code>library(ISLR)
library(gridExtra)</code></pre>
<pre><code>## 
## Attaching package: &#39;gridExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     combine</code></pre>
<pre class="r"><code>ipa_ale_dataset$Style = as.factor(ipa_ale_dataset$Style)
splitpercent = .70
trainIndices = sample(1:dim(ipa_ale_dataset)[1], round(splitpercent * dim(ipa_ale_dataset)[1]))
ipa_ale_train = ipa_ale_dataset[trainIndices,]
ipa_ale_test = ipa_ale_dataset[-trainIndices,]</code></pre>
</div>
<div id="train-and-test-logistic-regression-model-and-output-its-performance-metrics.-this-model-is-capable-of-ascertaining-the-statistical-significance-of-the-relationships.-it-confirms-our-intuitions-that-ibu-is-significantly-correlated-to-style-while-abv-is-not." class="section level1">
<h1>Train and test logistic regression model and output its performance metrics. This model is capable of ascertaining the statistical significance of the relationships. It confirms our intuitions that IBU is significantly correlated to style, while ABV is not.</h1>
<pre class="r"><code>logistic_regression_model = glm(Style ~ ABV + IBU,  family = binomial(link = &#39;logit&#39;), data = ipa_ale_train)
summary(logistic_regression_model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Style ~ ABV + IBU, family = binomial(link = &quot;logit&quot;), 
##     data = ipa_ale_train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.6426  -0.4309  -0.2022   0.4853   2.5667  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -5.560978   0.557903  -9.968   &lt;2e-16 ***
## ABV         -14.590989  10.629855  -1.373     0.17    
## IBU           0.114280   0.007492  15.254   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1395.72  on 1073  degrees of freedom
## Residual deviance:  686.34  on 1071  degrees of freedom
## AIC: 692.34
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<pre class="r"><code>fitted.results = predict(logistic_regression_model, newdata = subset(ipa_ale_test, select = c(7, 8)), type = &#39;response&#39;)
log.probs = as.data.frame(fitted.results)$fitted.results
ipa_ale_test$Prob_IPA = log.probs
fitted.results = ifelse(fitted.results &gt; 0.5, &#39;IPA&#39;, &#39;Ale&#39;)

misclass_error = mean(fitted.results != ipa_ale_test$Style)
print(paste(&#39;Accuracy is &#39;, 1 - misclass_error))</code></pre>
<pre><code>## [1] &quot;Accuracy is  0.895652173913044&quot;</code></pre>
</div>
<div id="this-model-is-less-accurate-than-the-previous-cross-validated-model-but-it-has-the-benefit-of-providing-hard-statistical-evidence-to-support-our-suspicions-that-ibu-is-correlated-with-beer-style-and-abv-is-not-significantly-correlated." class="section level1">
<h1>This model is less accurate than the previous cross validated model, but it has the benefit of providing hard statistical evidence to support our suspicions: that IBU is correlated with beer style, and ABV is not significantly correlated.</h1>
</div>
<div id="this-plots-the-performance-of-the-logistic-regression-model-based-on-a-beers-abv-and-ibu.-this-model-confirms-the-previous-ibu-boundary-between-ipas-and-ales-as-somewhere-between-45-75." class="section level1">
<h1>This plots the performance of the logistic regression model based on a beers ABV and IBU. This model confirms the previous IBU boundary between IPAs and ales as somewhere between ~45-75.</h1>
<pre class="r"><code># Create dataframe of test set and model results
ipa_ale_test$Predicted_Style = fitted.results
ipa_ale_test$Correct = ifelse(ipa_ale_test$Style == ipa_ale_test$Predicted_Style, &#39;Correct Prediction&#39;, &#39;Incorrect Prediction&#39;)

ipa_ale_test %&gt;% ggplot(aes(x = IBU, y = ABV * 100, color = Correct)) + 
  geom_point(position = &#39;jitter&#39;) + 
  ggtitle(&#39;Logistic Model Performance&#39;) + 
  scale_color_manual(&#39;Model Performance&#39;, values = c(&#39;blue&#39;, &#39;red&#39;)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab(&#39;ABV (%)&#39;)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
</div>
<div id="plot-3d-results-of-model-performance-with-ipa-probability-as-the-z-axis.-this-shows-that-the-probability-of-being-an-ipa-increases-as-the-ibu-rating-increases-while-no-such-relationship-exists-with-abv.-this-confirms-our-previous-models.-the-point-at-which-the-model-considers-a-beer-to-be-an-ipa-is-at-an-ibu-of-55-indicating-this-to-be-a-likely-value-for-the-cutoff-ibu-between-ipas-and-ales." class="section level1">
<h1>Plot 3D results of model performance with IPA Probability as the z axis. This shows that the probability of being an IPA increases as the IBU rating increases, while no such relationship exists with ABV. This confirms our previous models. The point at which the model considers a beer to be an IPA is at an IBU of ~ 55, indicating this to be a likely value for the cutoff IBU between IPAs and Ales.</h1>
<pre class="r"><code>library(plotly)
logmodel_plot &lt;- plot_ly(ipa_ale_test, x = ~IBU, y = ~ABV, z = ~Prob_IPA *100, color = ~Correct, colors = c(&#39;blue&#39;, &#39;red&#39;))
logmodel_plot &lt;- logmodel_plot %&gt;% add_markers()
logmodel_plot &lt;- logmodel_plot %&gt;% layout(title = &#39;Logistic Regression Model Performance Probability&#39;, scene = list(xaxis = list(title = &#39;IBU&#39;),
                                  yaxis = list(title = &#39;ABV&#39;),
                                  zaxis = list(title = &#39;Probability of Being an IPA (%)&#39;)))
logmodel_plot</code></pre>
<div id="htmlwidget-c641c72630a4c91b7b05" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-c641c72630a4c91b7b05">{"x":{"visdat":{"24dc48452c9":["function () ","plotlyVisDat"]},"cur_data":"24dc48452c9","attrs":{"24dc48452c9":{"x":{},"y":{},"z":{},"color":{},"colors":["blue","red"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d","mode":"markers","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Logistic Regression Model Performance Probability","scene":{"xaxis":{"title":"IBU"},"yaxis":{"title":"ABV"},"zaxis":{"title":"Probability of Being an IPA (%)"}},"hovermode":"closest","showlegend":true},"source":"A","config":{"showSendToCloud":false},"data":[{"x":[85,100,93.32,67.6345514950166,67.6345514950166,57,93.32,57,72,65,104,67.6345514950166,86,75,75,77,61,65,90,85,67.6345514950166,70,69,93.32,63,67.6345514950166,67.6345514950166,103,67.6345514950166,75,90,67.6345514950166,93.32,99,67.6345514950166,90,70,90,115,87,75,70,65,93.32,67.6345514950166,67.6345514950166,67,70,85,94,67.6345514950166,88,60,100,110,65,67.6345514950166,70,64,65,60,60,67.6345514950166,60,67.6345514950166,70,94,100,60,67.6345514950166,70,67.6345514950166,60,67.6345514950166,85,60,93.32,67.6345514950166,67.6345514950166,67.6345514950166,67.6345514950166,68,70,70,70,90,70,69,75,62,67.6345514950166,67.6345514950166,67.6345514950166,60,67.6345514950166,115,61,65,70,92,74,75,65,60,65,65,120,90,67.6345514950166,73,66,87,69,60,75,75,80,100,93.32,100,72,67.6345514950166,67.6345514950166,93.32,60,67.6345514950166,64,135,95,88,67.6345514950166,67.6345514950166,67.6345514950166,80,100,70,70,65,67.6345514950166,65,65,86,68,62,67.6345514950166,67.6345514950166,67.6345514950166,67.6345514950166,70,86,60,67.6345514950166,95,67.6345514950166,75,67.6345514950166,67.6345514950166,67.6345514950166,82,75,70,80,85,100,83,65,65,93.32,67.6345514950166,19,42,13,27,24,30,19,29.8947368421053,20.6885245901639,28.3913043478261,23.875,36.2987012987013,28.3913043478261,25,29.6666666666667,28.3913043478261,10,29.8947368421053,44.9411764705882,30,36,50,25,44.9411764705882,50,45,44.9411764705882,20.6885245901639,24.8181818181818,26.9090909090909,44.9411764705882,23.875,12,44.9411764705882,20,48,47,23.875,35,20.983606557377,20,36.2987012987013,20,36.2987012987013,25,44.9411764705882,46,33,36.2987012987013,20.983606557377,19,44.9411764705882,44.9411764705882,20.6885245901639,20.6885245901639,36.2987012987013,16,20,20,20,20,20,20,20.6885245901639,20.6885245901639,18,30,18,36.2987012987013,32,36.2987012987013,42,36.2987012987013,24,20.983606557377,22,25,40,21,28.3913043478261,20,45,28.3913043478261,6,25,21,7,20,14,14,29.8947368421053,44.9411764705882,25,44.9411764705882,24.8181818181818,30,36.2987012987013,55,55,29,10,17,34,20,35,44.9411764705882,36,25,22,25,15,15,44.9411764705882,20.6885245901639,44.9411764705882,28.3913043478261,25,53,20,21,44.9411764705882,20.6885245901639,36,55,40,20,53,26.9090909090909,23,42,20.983606557377,44.9411764705882,44.9411764705882,30,35,40,28.3913043478261,12,36.2987012987013,55,24.2307692307692,44.9411764705882,36.2987012987013,30,50,45,35,20,18,23.875,23.875,44.9411764705882,40,28,45,16,24,24,36.2987012987013,44.9411764705882,20.6885245901639,20.6885245901639,34,20.6885245901639,28,42,20.6885245901639,44.9411764705882,44.9411764705882,35,32,20.983606557377,18,26.9090909090909,45,44.9411764705882,31.4,44.9411764705882,50,37,19,40,26,55,44,44.9411764705882,27,24.8181818181818,30,30,30,22,14,20,54,36.2987012987013,20.6885245901639,44.9411764705882,20.983606557377,24.8181818181818,36.2987012987013,20.983606557377,20.983606557377,19,55,29.8947368421053,44.9411764705882,36.2987012987013,35,20,36.2987012987013,44.9411764705882,23,24.8181818181818,28.3913043478261,19,42,44.9411764705882,20,45,35,54,20.983606557377,18,29.8947368421053,20.6885245901639,20.3333333333333,30,44.9411764705882,36.2987012987013,44.9411764705882,36.2987012987013,22,20.983606557377,44.9411764705882,29.8947368421053,27,42,36.2987012987013,20.6885245901639,26.9090909090909,36.2987012987013,44.9411764705882],"y":[0.075,0.08,0.097,0.077,0.07,0.05,0.093,0.065,0.058,0.072,0.06,0.06,0.072,0.064,0.064,0.075,0.07,0.069,0.085,0.07,0.07,0.07,0.063,0.08,0.075,0.045,0.05,0.091,0.05,0.075,0.099,0.072,0.083,0.062,0.072,0.075,0.059,0.085,0.075,0.072,0.066,0.065,0.072,0.099,0.065,0.07,0.052,0.06,0.068,0.07,0.069,0.07,0.067,0.099,0.085,0.065,0.075,0.066,0.063,0.077,0.07,0.07,0.045,0.07,0.06,0.067,0.061,0.068,0.061,0.061,0.06,0.063,0.062,0.085,0.087,0.043,0.082,0.027,0.062,0.075,0.065,0.07,0.07,0.062,0.062,0.065,0.063,0.069,0.072,0.062,0.067,0.045,0.071,0.071,0.06,0.092,0.062,0.068,0.08,0.094,0.074,0.07,0.065,0.06,0.068,0.068,0.08,0.068,0.065,0.076,0.068,0.073,0.069,0.065,0.09,0.09,0.08,0.063,0.092,0.063,0.065,0.0645275779376499,0.072,0.097,0.067,0.052,0.061,0.059,0.064,0.08,0.077,0.055,0.072,0.072,0.082,0.07,0.07,0.07,0.062,0.068,0.069,0.085,0.062,0.071,0.04,0.062,0.062,0.062,0.072,0.08,0.074,0.062,0.08,0.065,0.07,0.068,0.04,0.078,0.084,0.068,0.068,0.07,0.071,0.066,0.074,0.065,0.065,0.0873689320388349,0.068,0.048,0.042,0.04,0.065,0.06,0.063,0.047,0.062,0.061,0.09,0.06,0.06,0.067,0.082,0.098,0.09,0.055,0.045,0.058,0.09,0.099,0.056,0.08,0.052,0.09,0.055,0.055,0.045,0.08,0.051,0.048,0.068,0.044,0.052,0.048,0.06,0.059,0.08,0.049,0.047,0.047,0.05,0.05,0.057456,0.052,0.06,0.06,0.065,0.068,0.05,0.047,0.057,0.065,0.058,0.0484105263157895,0.057456,0.048,0.039,0.039,0.039,0.039,0.039,0.039,0.048,0.052,0.052,0.054,0.042,0.061,0.07,0.05,0.057,0.055,0.052,0.049,0.075,0.05,0.05,0.052,0.055,0.05,0.065,0.055,0.045,0.05,0.051,0.052,0.05,0.059,0.059,0.055,0.05,0.055,0.055,0.06,0.061,0.057456,0.056,0.056,0.04,0.05,0.04,0.04,0.05,0.05,0.051,0.045,0.08,0.047,0.049,0.058,0.058,0.06,0.055,0.058,0.069,0.053,0.06,0.053,0.052,0.042,0.046,0.057,0.06,0.055,0.049,0.075,0.05,0.052,0.054,0.049,0.054,0.058,0.055,0.055,0.06,0.065,0.05,0.055,0.063,0.08,0.06,0.059,0.055,0.05,0.044,0.058,0.055,0.052,0.05,0.073,0.061,0.053,0.056,0.054,0.05,0.051,0.051,0.051,0.047,0.047,0.047,0.078,0.047,0.047,0.057,0.048,0.04,0.04,0.048,0.052,0.043,0.045,0.08,0.035,0.045,0.045,0.052,0.063,0.063,0.045,0.05,0.051,0.056,0.066,0.05,0.052,0.045,0.066,0.054,0.054,0.07,0.053,0.051,0.06,0.08,0.05,0.055,0.051,0.047,0.062,0.053,0.053,0.054,0.073,0.04,0.063,0.056,0.057,0.058,0.052,0.0545774058577406,0.052,0.055,0.05,0.05,0.063,0.052,0.046,0.065,0.065,0.08,0.06,0.06,0.07,0.047,0.06,0.054,0.05,0.057456,0.055,0.057456,0.044,0.05,0.052,0.054,0.056,0.062,0.045,0.05,0.057,0.057456,0.043],"z":[95.5149276401693,99.0984721079511,97.5596885899878,73.9778242799692,75.8953969013617,55.5631876943249,97.6948490645685,50.1146953327635,86.0677693650386,69.3534064800532,99.5716616794524,78.4631405096575,96.1453512724233,88.8570830959258,88.8570830959258,89.5133528792389,59.5982787017585,70.2758155911068,97.0229648389881,95.8172862932655,75.8953969013617,80.4911261402782,80.2997325655762,98.0855046625546,63.2826096973055,81.9317146535023,80.8264570922572,99.2476101487675,80.8264570922572,87.1660884057049,96.372740424945,75.3575069481459,98.0015522642816,99.2218048658194,75.3575069481459,97.4166992383308,82.8889654053792,97.0229648389881,99.8479111632191,96.5472502879146,88.5648514690003,81.6113160676501,69.3534064800532,97.4892405583455,77.2047386731147,75.8953969013617,79.2008390614095,82.6810248976414,95.9326895628419,98.4632386314172,76.1613191261862,96.9948311448768,57.889695212035,98.8138787371656,99.6888788265146,71.4803787696001,74.535653192554,81.3913347505063,69.7143525390643,67.7812888349901,56.8190920689813,56.8190920689813,81.9317146535023,56.8190920689813,78.4631405096575,81.1693290333067,98.6498019962584,99.2421782523033,60.0078654955724,78.2155508730711,82.6810248976414,77.7142319857848,59.6571988802301,71.6687297662042,94.7021521156344,66.1151666938207,98.0299296039704,85.499975445107,77.9659142280202,74.535653192554,77.2047386731147,76.6511486194863,80.4911261402782,82.2591600064382,82.2591600064382,97.7595619090573,82.045223715615,78.8780156787765,87.6478540341306,65.016454736174,76.6870915938106,81.9317146535023,75.6274575727416,56.4607519719303,78.4631405096575,99.8051785400763,62.3746804596221,70.5797010749166,78.0976772188243,97.2913549822322,86.0089675842925,87.9603343319053,71.4803787696001,60.3575095028752,70.5797010749166,70.5797010749166,99.9075548835891,97.6616573586395,77.2047386731147,84.1918520510877,72.8957157751057,96.4982789865683,78.8780156787765,58.5993953222875,84.5124124037012,84.5124124037012,91.7901563836056,99.2951207045552,97.7274805063398,99.2951207045552,84.7973323861098,77.3258230392464,75.3575069481459,97.5596885899878,57.889695212035,80.3701428381192,70.3269169975935,99.9877343677476,98.7405646471544,96.5390819715492,73.9778242799692,79.6703656364994,75.3575069481459,92.6279772517782,99.0720238465849,80.4911261402782,80.4911261402782,69.9701267489737,77.9659142280202,70.5797010749166,70.2758155911068,95.3774619279522,78.6749893026675,61.973973227023,82.9866706947,77.9659142280202,77.9659142280202,77.9659142280202,80.0288031948853,95.6886694558555,55.3818201837119,77.9659142280202,98.4146376204409,77.2047386731147,87.9603343319053,76.4252189526842,82.9866706947,73.6959572697012,92.9848725946327,88.2659679117839,80.9452948010281,92.8247858081516,95.7584165590708,99.2638129769017,94.5036706201345,71.4803787696001,71.4803787696001,97.8728071110396,76.4252189526842,1.64633384592756,20.197036113471,0.938723290860208,3.155917952378,2.42755866435092,4.5139833251629,1.67012745720922,4.52503673822988,1.65165714218619,2.5841334992126,2.39395166025251,9.21042031443408,3.5777388689428,1.9831937484879,2.65820360273533,2.5841334992126,0.53746159351622,5.72598214319117,21.9024204938838,3.08956607964135,5.25806666647298,33.9829127728812,2.04072153284218,23.4366767810897,23.8640138841916,22.7783986783374,22.6603695986705,2.07695150095487,1.99959554088584,3.80545109655036,24.5001391271094,2.13583670253251,0.79105382781956,23.4366767810897,1.84197817241811,27.8687689735407,25.9096499568367,1.79894985263971,9.31197427678591,2.08620532726557,1.86854561155177,10.5053035097671,1.78995057604562,9.52555235048166,3.03923452871312,21.407349592523,23.5134707593201,6.07599213285198,8.27970036503698,1.99864152183706,1.67012745720922,22.1530261258453,20.2055145548287,1.72428645665839,1.97812021568526,9.52555235048166,1.17409748562534,2.09505006750118,2.09505006750118,2.09505006750118,2.09505006750118,2.09505006750118,2.09505006750118,1.98976821110258,1.87908114248091,1.38891168930535,5.11503545194644,1.60359964944833,9.08913298254314,5.09132964707021,10.5053035097671,16.8977736591358,9.83890060094656,2.71994826609208,2.02742189505197,1.5655794211052,3.12641846966275,15.1959622575672,1.94584774438487,4.23337688492215,1.78995057604562,20.3141157336667,4.23337688492215,0.39428902068073,3.12641846966275,1.973883200973,0.399087007578887,1.78995057604562,0.798699534059935,0.798699534059935,4.98736850755454,23.964368300256,2.91285945958492,22.6603695986705,2.65916377328342,4.64144702724178,9.52555235048166,47.6853059422461,47.6853059422461,5.56987549469642,0.577902731432269,1.47471027517873,9.45686312112751,1.78995057604562,9.1894849917915,23.6995100501037,10.8759054513323,2.04072153284218,2.33715489679603,3.17091333763128,0.907558666110158,0.907558666110158,21.407349592523,1.80005108871297,21.9024204938838,3.4784212247843,2.99653022187475,40.6228523254411,1.71460365430432,1.94584774438487,26.1554218715886,2.04748272139462,9.29132561478925,46.2317103873523,14.2794842180571,1.81578148606148,35.4699877918165,3.85922489854762,2.43336277065619,17.5213888238063,2.02742189505197,22.9171027773766,21.9024204938838,5.0446815586194,8.59853132984794,13.4095395087856,3.67978417009388,0.72522604155622,9.83890060094656,45.1455669741819,1.87220019387954,21.407349592523,9.33315997235673,5.0446815586194,35.9736074589453,25.72395776591,8.26068808647123,1.6661127474747,1.38891168930535,2.75964391557501,1.98855326012788,21.1628862131084,14.6404214706809,3.99934806024578,23.0360707806019,1.14071528405994,2.75882303584268,2.75882303584268,10.3689119594717,24.7710401140192,2.01842344057569,2.01842344057569,5.65966972662657,2.01842344057569,4.5351293933019,16.8977736591358,1.98976821110258,26.7229619826452,26.7229619826452,9.43592660680807,6.52082223312091,2.20881837266984,1.53597437796947,2.5256843986594,28.3118141222767,25.3188403576046,6.72845501656728,23.4366767810897,31.7303277229071,9.51910980709257,1.71873316674169,15.1959622575672,3.44287013546178,47.6853059422461,18.3075535736351,23.964368300256,3.79009941390068,3.2883687501146,4.32902425427265,5.11503545194644,5.11503545194644,1.68207268942689,0.871137888420527,1.76448052714636,43.4061716895783,7.04348442822815,1.93364844404574,22.6603695986705,1.97026148576665,3.19681766412257,8.96928503398324,1.91468114188843,1.91468114188843,1.51041724299016,41.5639253210353,6.13275976254164,20.6801049786217,9.71022229045032,8.37193851740712,1.59589399834793,10.2340886993676,22.7686147999513,2.43336277065619,2.85466974441624,4.53922436342558,1.59974225975241,15.7037803465729,23.4366767810897,1.89548884170451,20.3141157336667,7.51893075939124,36.4214540988696,1.73199678112978,1.23778555951136,4.04667520886367,2.01842344057569,1.60994933678768,5.11503545194644,23.964368300256,9.52555235048166,22.6603695986705,9.52555235048166,2.43918040722309,1.99864152183706,23.4366767810897,5.0569656719345,3.58292441383048,15.8978993418659,11.211230283906,1.93364844404574,3.49762285333525,9.52555235048166,25.8745882884393],"type":"scatter3d","mode":"markers","name":"Correct Prediction","marker":{"color":"rgba(0,0,255,1)","line":{"color":"rgba(0,0,255,1)"}},"textfont":{"color":"rgba(0,0,255,1)"},"error_y":{"color":"rgba(0,0,255,1)"},"error_x":{"color":"rgba(0,0,255,1)"},"line":{"color":"rgba(0,0,255,1)"},"frame":null},{"x":[50,57,40,48.8333333333333,57,48,55,54.7142857142857,45,40,40,42,40,55,51,52,52,45,54.7142857142857,48.8333333333333,44,40,65.4166666666667,70,60,60,60,65,60,70,65,68,68.9,69,72,80,65,60,60,60,78,68.9,65,95,68.9,68.9,68.9,65],"y":[0.045,0.093,0.038,0.062,0.085,0.048,0.059,0.066,0.062,0.07,0.055,0.059,0.055,0.05,0.069,0.065,0.065,0.067,0.06,0.06,0.065,0.06,0.0765384615384615,0.07,0.058,0.058,0.06,0.065,0.058,0.08,0.065,0.07,0.062,0.08,0.086,0.065,0.065,0.055,0.072,0.055,0.076,0.074,0.065,0.071,0.07,0.07,0.0689714285714286,0.065],"z":[37.6705620210906,40.0361310463728,17.5922425527929,29.2157454558974,42.8681663450762,31.5206668350694,46.5946062871314,43.2608737635562,21.0319024835566,11.8038955396269,14.2794842180571,16.4919370208149,14.2794842180571,49.8722989009001,32.3122615439909,36.1972311048069,36.1972311048069,19.8458229827622,45.4211280027169,29.8228723702922,18.5267846666185,13.4095395087856,68.9565748957853,80.4911261402782,61.0535997667923,61.0535997667923,60.3575095028752,71.4803787696001,61.0535997667923,78.0976772188243,71.4803787696001,76.6511486194863,80.3497202071064,76.0803052795563,80.4141438669577,93.2957695355782,71.4803787696001,62.0892648188014,56.1017356438571,62.0892648188014,90.4129513081079,77.4379060456159,71.4803787696001,98.6070176937129,78.4412660591689,78.4412660591689,78.6939799478687,71.4803787696001],"type":"scatter3d","mode":"markers","name":"Incorrect Prediction","marker":{"color":"rgba(255,0,0,1)","line":{"color":"rgba(255,0,0,1)"}},"textfont":{"color":"rgba(255,0,0,1)"},"error_y":{"color":"rgba(255,0,0,1)"},"error_x":{"color":"rgba(255,0,0,1)"},"line":{"color":"rgba(255,0,0,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
<div id="to-summarize-the-difference-between-ipas-and-ales-are-that-ipas-tend-to-have-a-higher-ibu-rating-than-ales-while-both-styles-of-beers-have-the-same-range-of-abvs.-this-was-confirmed-with-multiple-models." class="section level1">
<h1>To summarize: the difference between IPAs and ales are that IPAs tend to have a higher IBU rating than ales, while both styles of beers have the same range of ABVs. This was confirmed with multiple models.</h1>
<div id="section-23" class="section level148">
<p></p>
</div>
<div id="question-9" class="section level61">
<p>Question 9</p>
<div id="section-24" class="section level148">
<p></p>
</div>
</div>
<div id="find-one-other-useful-piece-of-information-in-the-data.-convince-them-why-its-important-and-back-it-up." class="section level4">
<h4>9. Find one other useful piece of information in the data. Convince them why it’s important and back it up.</h4>
</div>
</div>
<div id="we-will-determine-which-beer-styles-are-popular-across-all-50-states.-the-most-brewed-beer-in-each-state-will-be-determined-and-plotted.-this-will-give-inight-into-which-beers-are-in-demand-by-location.-this-information-can-be-very-valuable-for-marketing-or-brewing-purposes.-the-beer-styles-were-condensed-into-8-distinct-groups-that-are-sufficiently-different-to-warrant-its-own-grouping." class="section level1">
<h1>We will determine which beer styles are popular across all 50 states. The most brewed beer in each state will be determined and plotted. This will give inight into which beers are in demand by location. This information can be very valuable for marketing or brewing purposes. The beer styles were condensed into 8 distinct groups that are sufficiently different to warrant its own grouping.</h1>
</div>
<div id="this-code-condenses-beer-styles-into-a-few-common-types-such-as-ipa-ale-pale-ale-lager-stout-pilsner-wheat-beer-and-porter.-it-then-determines-the-most-brewed-beer-by-state-and-plots-a-heat-map" class="section level1">
<h1>This code condenses beer styles into a few common types, such as: IPA, Ale, Pale Ale, Lager, Stout, Pilsner, Wheat Beer, and Porter. It then determines the most brewed beer by state, and plots a heat map</h1>
<pre class="r"><code># Filter into multiple groups
ipa_dataset = dataset %&gt;% filter(grepl(&#39;.*IPA.*&#39;, dataset$Style))
wheat_dataset = dataset %&gt;% filter(grepl(&#39;.*Wheat.*&#39;, dataset$Style) | grepl(&#39;.*Hefeweizen.*&#39;, dataset$Style) | grepl(&#39;.*Witbier.*&#39;, dataset$Style))
ale_dataset = dataset %&gt;% filter(grepl(&#39;.* Ale.*&#39;, dataset$Style))
ale_dataset = ale_dataset %&gt;% filter(!grepl(&#39;.*IPA.*&#39;, ale_dataset$Style))
ale_dataset = ale_dataset %&gt;% filter(!grepl(&#39;.* Pale.*&#39;, ale_dataset$Style))
ale_dataset = ale_dataset %&gt;% filter(!grepl(&#39;.*Wheat*&#39;, ale_dataset$Style))
pale_ale_dataset = dataset %&gt;% filter(grepl(&#39;.* Pale.*&#39;, dataset$Style))
pale_ale_dataset = pale_ale_dataset %&gt;% filter(!grepl(&#39;.*IPA.*&#39;, pale_ale_dataset$Style))
lager_dataset = dataset %&gt;% filter(grepl(&#39;.*Lager.*&#39;, dataset$Style))
stout_dataset = dataset %&gt;% filter(grepl(&#39;.*Stout.*&#39;, dataset$Style))
pilsner_dataset = dataset %&gt;% filter(grepl(&#39;.*Pilsner.*&#39;, dataset$Style))
porter_data = dataset %&gt;% filter(grepl(&#39;.*Porter.*&#39;, dataset$Style))

ipa_dataset$Style = c(&#39;IPA&#39;)
ale_dataset$Style = c(&#39;Ale&#39;)
pale_ale_dataset$Style = c(&#39;Pale Ale&#39;)
lager_dataset$Style = c(&#39;Lager&#39;)
stout_dataset$Style = c(&#39;Stout&#39;)
pilsner_dataset$Style = c(&#39;Pilsner&#39;)
wheat_dataset$Style = c(&#39;Wheat Beer&#39;)
porter_data$Style = c(&#39;Porter&#39;)

styled_dataset = rbind(ipa_dataset, ale_dataset, pale_ale_dataset, lager_dataset, stout_dataset, pilsner_dataset, wheat_dataset, porter_data)
styled_dataset = styled_dataset[order(styled_dataset$State),]
styled_dataset$Style = as.factor(styled_dataset$Style)
styled_dataset$State = as.factor(styled_dataset$State)

# Find favorite beer in each state, and create a table containing the statistics.
beer_counts = styled_dataset %&gt;% group_by(State) %&gt;% count(Style)
beer_counts = beer_counts[with(beer_counts, order(beer_counts$State, -beer_counts$n)),]

beer_count_spread = spread(beer_counts, Style, n)
beer_count_spread[is.na(beer_count_spread)] = 0

# Save the data for dc before removing the DC observations. Necessary for heat map to work as written
beer_counts_dc = beer_counts
beer_counts = subset(beer_counts, beer_counts$State != &#39; DC&#39;)

row = 1
for (row in 1:nrow(beer_count_spread)){
  beer_count_spread$Total[row] = sum(beer_count_spread[row ,2:9])
  row = row + 1
}</code></pre>
<pre><code>## Warning: Unknown or uninitialised column: &#39;Total&#39;.</code></pre>
<pre class="r"><code>favorites = data.frame(matrix(&#39;&#39;, ncol = 2, nrow = 50))
names(favorites) = c(&#39;State&#39;, &#39;Style&#39;)
levels(favorites$State) = levels(styled_dataset$State)
levels(favorites$Style) = levels(styled_dataset$Style)
favorites$State = max_data2$abb
favorites$Style = c(NA)
favorites$Style = as.factor(favorites$Style)
faclevels = addNA(levels(beer_counts$Style))
levels(favorites$Style) = faclevels

row  =1
faverow = 1
for (row in 1:nrow(beer_counts)) {
  state = beer_counts$State[row]
  style = beer_counts$Style[row]
  
  if(is.na(favorites[favorites$State == state,]$Style)) {
    favorites$Style[faverow] = style
    faverow = faverow + 1
  }
  row = row + 1
}

levels(favorites$Style) = levels(styled_dataset$Style)

# Create Heatmap of favorite beers by State
library(ggplot2)
library(maps)
library(dplyr)
library(mapproj)

# Create a dataframe containing state information and manipulate variables to merge dataframes later
lookup = data.frame(abb = state.abb, State = state.name)
colnames(favorites)[1] = &quot;abb&quot;
favorites2 = merge(favorites,lookup, by =&quot;abb&quot;, all.x = TRUE, no.dups = F)
levels(favorites2$State) = levels(lookup$State)
levels(lookup$abb) = levels(favorites2$abb)

for (row in 1:nrow(favorites2)){
  abb = as.character(favorites2$abb[row])
  abb = trimws(abb)
  favorites2$State[row] = state.name[which(state.abb == abb)]
}

favorites2$region &lt;- tolower(favorites2$State)
states &lt;- map_data(&quot;state&quot;)

map.df &lt;- merge(states,favorites2, by=&quot;region&quot;, all.x=T)
map.df &lt;- map.df[order(map.df$order),]
map.df$region &lt;- as.factor(map.df$region)

row = 1
for (row in 1:nrow(map.df)) {
  if (map.df$region[row] == &#39;district of columbia&#39;) {
  map.df$Style[row] = &#39;Ale&#39;
  row = row + 1
  }
}

# Plot the heatmap
ggplot(map.df, aes(x=long,y=lat,group=group)) + 
  geom_polygon(aes(fill=Style)) +
  geom_path() + 
  ggtitle(&#39;Most Brewed Beer in Each State&#39;) +  
  coord_map() + 
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values = c(&#39;red2&#39;, &#39;orange2&#39;, &#39;chartreuse3&#39;, &#39;blue3&#39;, &#39;cyan1&#39;, &#39;orchid&#39;, &#39;springgreen2&#39;, &#39;turquoise3&#39;), drop = FALSE)</code></pre>
<p><img src="Brewery_Case_Study_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
</div>
<div id="the-most-noticeable-trend-is-the-popularity-of-ales-in-the-midwest-and-of-ipas-on-the-west-coast-and-in-new-england.-it-should-be-noted-that-the-most-brewed-style-by-region-is-likely-indicative-of-local-preferences-since-microbreweries-tend-to-have-smaller-distribution-zones-than-large-brewers.-this-map-provides-valuable-information-for-targeted-marketing-for-beer-products-as-well-as-an-indication-of-what-types-of-beers-should-be-created-based-on-brewery-location." class="section level1">
<h1>The most noticeable trend is the popularity of ales in the midwest, and of IPAs on the west coast and in New England. It should be noted that the most brewed style by region is likely indicative of local preferences, since microbreweries tend to have smaller distribution zones than large brewers. This map provides valuable information for targeted marketing for beer products, as well as an indication of what types of beers should be created based on brewery location.</h1>
<div id="section-25" class="section level143">
<p></p>
</div>
<div id="conclusion" class="section level64">
<p>Conclusion</p>
<div id="section-26" class="section level143">
<p></p>
</div>
</div>
</div>
<div id="there-were-many-valuable-insights-gained-from-the-data-provided-by-budweiser.-the-distribution-of-breweries-across-the-country-is-affected-both-by-population-demographics-and-the-legal-aspects-of-alcohol-brewing-and-distribution.-the-strength-of-beers-is-also-to-some-extent-determined-by-law-and-local-preference-while-the-bitterness-of-local-beers-are-determined-almost-wholly-by-local-preference-and-new-trends.-these-trends-have-been-determined-and-summarized-above-which-can-aid-in-targeted-marketing-for-specific-beers-or-for-consideration-in-creating-new-brews.-a-definite-distinction-was-found-between-ipas-and-ales-based-solely-on-ibu-rating.-while-ipas-tend-to-have-a-higher-ibu-rating-than-other-ales-there-is-no-such-distinction-in-terms-of-alcohol-content." class="section level1">
<h1>There were many valuable insights gained from the data provided by Budweiser. The distribution of breweries across the country is affected both by population demographics and the legal aspects of alcohol brewing and distribution. The strength of beers is also to some extent determined by law, and local preference, while the bitterness of local beers are determined almost wholly by local preference and new trends. These trends have been determined and summarized above, which can aid in targeted marketing for specific beers, or for consideration in creating new brews. A definite distinction was found between IPAs and ales, based solely on IBU rating. While IPAs tend to have a higher IBU rating than other ales, there is no such distinction in terms of alcohol content.</h1>
<div id="section-27" class="section level143">
<p></p>
</div>
<div id="section-28" class="section level143">
<p></p>
</div>
<div id="section-29" class="section level143">
<p></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
